WS + N trackers + remove global BOOTNODES
streamr-dev/network-old pull request #132
Opened 2018-10-17 11:42 UTC by mirpo

- Add support of Multiple trackers
- Add setBootnodes function for the Node
- Remove PEER_DISCOVERED event
- Remove libp2p files add WS

fixes #125, #122, #114, #113

2018-10-17 13:51 UTC, harbu requested changes

2018-10-17 13:51 UTC, harbu commented on .idea/jsLibraryMappings.xml
> -    <file url="PROJECT" libraries="{@types/jest}" />
Let's keep this in. Allows IntelliJ to know that tests are Jest.

2018-10-17 13:51 UTC, harbu commented on publisher.js
> +        client.protocols.nodeToNode.endpoint.connect(nodeAddress)
Hmm.. shouldn't the client do this internally?

2018-10-17 13:51 UTC, harbu commented on src/composition.js
> +async function WsNode(host, port) {
Talked about moving this to connection layer in meeting.

2018-10-17 13:51 UTC, harbu commented on src/composition.js
> +    return createEndpoint(host, port, id, false).then((endpoint) => {
Can remove last boolean argument from `createEndpoint`.

2018-10-17 13:51 UTC, harbu commented on src/composition.js
> +    return createEndpoint(host, port, id, true).then((endpoint) => {
Can remove last boolean argument from `createEndpoint`.

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +            const parameters = url.parse(req.url, true)
We might want to add validation here that parameters were indeed given.

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +            console.error('Sorry, the web socket at "%s" is un-available')
%s, not assigned to.

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +            console.error('Sorry, the web socket at "%s" is un-available')
Also return false here

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +        // debug('received from peer %s message with data "%s"', sender, message)
Lets keep this?

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +            return
Maybe we could add `debug` here to see if this happens a lot.

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +    async onReceive(sender, message) {
Can remove `async`

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +    connect(peerAddress) {
We could make this return a Promise so that user's can wait for connection be done (or refused). Maybe make testing easier?

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +        ws.peerId = peerId
Let's refactor later to  `Peer` (or `Connection`?) object

2018-10-17 13:51 UTC, harbu commented on src/connection/WsEndpoint.js
> +        this.emit(Endpoint.events.PEER_CONNECTED, ws.peerId)
Let us move this emit to be last line of this function.

2018-10-17 13:51 UTC, harbu commented on src/logic/Client.js
> +        this.id = getIdShort(nodeToNode.endpoint.id)
I think we need better way still. Maybe pass id in constructor or something. Dunno.

2018-10-17 13:51 UTC, harbu commented on src/logic/Node.js
> +        if (tracker) {
Think we can get rid of this check now and assume that `tracker` is always given here.

2018-10-17 13:51 UTC, harbu commented on src/logic/Node.js
> +    setBootnodes(bootstrapNodes, delay = 3000) {
We should probably rename `setBootTrackers` and first argument to `bootstrapTrackers` for now because that is our current assumption in the code.

Later we can rename to `setBootPeers` and `bootstrapPeers` when that is supported.

2018-10-17 13:51 UTC, harbu commented on src/logic/Node.js
> +        this._peerDiscoveryTimer = setInterval(() => {
Let's make this execute immediately and then wait for `delay` to make it faster. https://stackoverflow.com/questions/6685396/execute-the-setinterval-function-without-delay-the-first-time

2018-10-17 13:51 UTC, harbu commented on src/logic/Node.js
> +        this._peerDiscoveryTimer = setInterval(() => {
Rename to `trackerDiscoveryInterval`.

2018-10-17 13:51 UTC, harbu commented on src/logic/Node.js
> +    _isTracker(tracker) {
I think these need to be moved to protocol layer later on. We can't just rely on bootstrap list for checking if a peer is a tracker or a node (or both?)

2018-10-17 13:51 UTC, harbu commented on src/protocol/TrackerNode.js
> +    sendPeerMessage(tracker) {
what about `requestPeers`

2018-10-17 13:51 UTC, harbu commented on src/util.js
> +// TODO remove both
Will do

2018-10-17 13:51 UTC, harbu commented on subscriber.js
> +const { createEndpoint } = require('./src/composition')
Could just use `createClient` or `startClient` ?

2018-10-17 13:51 UTC, harbu commented on test/integration/ws-endpoint.test.js
> +        Promise.all(promises)
You are not awaiting for them? Needs to be fixed I think.

2018-10-17 16:28 UTC, mirpo commented on .idea/jsLibraryMappings.xml
> -    <file url="PROJECT" libraries="{@types/jest}" />
ok, maybe auto refactoring broke it

2018-10-17 16:29 UTC, mirpo commented on publisher.js
> +        client.protocols.nodeToNode.endpoint.connect(nodeAddress)
yep, but it was before that PR

2018-10-17 16:30 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        // debug('received from peer %s message with data "%s"', sender, message)
nope :)

2018-10-17 16:30 UTC, mirpo commented on src/connection/WsEndpoint.js
> +    connect(peerAddress) {
agree

2018-10-17 16:32 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        ws.peerId = peerId
I already created empty Peer object

2018-10-17 16:40 UTC, mirpo commented on src/protocol/TrackerNode.js
> +    sendPeerMessage(tracker) {
true

2018-10-17 16:51 UTC, mirpo commented on test/integration/ws-endpoint.test.js
> +        Promise.all(promises)
hmmm, I'm pushing to array above

2018-10-18 10:44 UTC, harbu commented on src/util.js
> +// TODO remove both
Will remove in a later PR. Leave as is for now.

2018-10-18 12:25 UTC, harbu approved these changes

2018-10-18 12:26 UTC, merged