Limit number of connections per stream
streamr-dev/network-old pull request #169
Opened 2019-01-18 14:06 UTC by mirpo

Added number of connections for the stream. But we have InboundNodesForStream and OutboundNodesForStream, so now I check sum of both. But maybe we need separate limits? 
And also now we can get disconnection reason on protocol level.
@harbu with MAX_NUM_OF_NODES_PER_STREAM = 6 message-duplication.test.js is failing. So I removed 5th node. But maybe we want to add more tests for some edge cases.

2019-01-18 16:13 UTC, harbu requested changes
LGTM; few ideas + I think the test should still work so we should figure out what is the issue?

2019-01-18 16:13 UTC, harbu commented on src/protocol/NodeToNode.js
> +    sendDisconnectionMessage(receiverNodeId, reason) {
What about renaming to `disconnectFromNode` or `disconnect` since you are actually disconnecting (not just sending msg)?

2019-01-18 16:13 UTC, harbu commented on src/logic/Node.js
> +        if (this.streams.getInboundNodesForStream(streamId).length + this.streams.getOutboundNodesForStream(streamId).length >= MAX_NUM_OF_NODES_PER_STREAM) {
Btw each connected node will have an entry in both `inboundNodes` and `outboundNodes`, so now the limit becomes `MAX_NUM_OF_NODES_PER_STREAM / 2` WebSocket connections to nodes (per stream)

2019-01-18 16:13 UTC, harbu commented on test/integration/message-duplication.test.js
>              startNetworkNode(LOCALHOST, 30353, 'node-2'),
Hmm.. I think this test should still work though? Because it is only checking upper limits not exact numbers. I'll try it out before change and see if I can see what the issue is.

2019-01-21 08:37 UTC, mirpo commented on test/integration/message-duplication.test.js
>              startNetworkNode(LOCALHOST, 30353, 'node-2'),
I put original test back, lets check together.

2019-01-24 13:09 UTC, harbu requested changes

2019-01-24 13:09 UTC, harbu commented on src/logic/Node.js
> +                this.protocols.nodeToNode.disconnectFromNode(source, disconnectionReasons.MAX_INBOUND_CONNECTIONS)
Method `nodeToNode.disconnectFromNode` may be invoked the 2nd time here if the earlier `else` block got executed?

2019-01-24 13:09 UTC, harbu commented on src/logic/Node.js
> +        this._handleBufferedMessages(streamId)
I think this code should get executed only if `disconnectFromNode` was not executed.

2019-01-24 13:09 UTC, harbu commented on test/integration/connection-limits.test.js
> + * This test verifies that on receiving a duplicate message, it is not re-emitted to the node's subscribers.
This comment needs to be removed or re-written

2019-01-24 13:09 UTC, harbu commented on test/integration/connection-limits.test.js
> +describe('duplicate message detection and avoidance', () => {
Better description?

2019-01-24 13:16 UTC, mirpo commented on src/logic/Node.js
> +                this.protocols.nodeToNode.disconnectFromNode(source, disconnectionReasons.MAX_INBOUND_CONNECTIONS)
Yes, but we check in WsEndpoint.close " if (!this.isConnected(recipientAddress))

2019-01-24 18:24 UTC, ptesavol approved these changes
Looks ok. Does the test go through now?

2019-01-25 09:18 UTC, merged