Add instructions from tracker to node to reconnect
streamr-dev/network-old pull request #177
Opened 2019-02-13 14:34 UTC by mirpo

I added:
- Instructions to reconnect from tracker
- Function for node to reconnect to the new nodes from tracker
- Added some check for ws.OPEN, minor additions to disconnect functions and etc.
- Added new disconnection reasons
- Added test for reconnection instructions, but super simple only with two nodes.

TODO @harbu:
- Check tests, we have weird situation when PeerBook raises and Error, especially on shutting down. Please check tests with --detectOpenHandles
- I commented part of message-propagation.test.js

2019-02-14 13:07 UTC, harbu requested changes
Looking good; I'll look into the tests next.

2019-02-14 13:07 UTC, harbu commented on src/connection/WsEndpoint.js
> +                        resolve()
Should this be `reject()` ?

2019-02-14 13:07 UTC, harbu commented on src/connection/WsEndpoint.js
> +                    if (ws.readyState === ws.OPEN) {
So this check is here in case we have disconnected but the disconnection hasn't yet been finalized?

2019-02-14 13:07 UTC, harbu commented on src/logic/Node.js
> +        const alreadyConnectedNode = [...this.streams.getAllOutboundNodes()]
`alreadyConnectedNodes`

2019-02-14 13:07 UTC, harbu commented on src/connection/WsEndpoint.js
> +                    if (ws.readyState === ws.OPEN) {
Maybe a code comment would be good here to make sure no one deletes it by accident etc.

2019-02-14 13:07 UTC, harbu commented on test/integration/connection-limits.test.js
> +                node.setConnectionLimitsPerStream(limits.maxInBound + 1, limits.maxOutBound + 1)
Why this change?

2019-02-14 13:07 UTC, harbu commented on test/integration/tracker-node-reconnect-instructions.test.js
> +    it('init tracker and nodes, tracker receives stream info', async (done) => {
Maybe change to `beforeAll` since no assertions and this is assumed to be ran before tests?

2019-02-14 13:07 UTC, harbu commented on test/integration/tracker-node-reconnect-instructions.test.js
> +    it('init tracker and nodes, tracker receives stream info', async (done) => {
You can remove `done()` from end of this function is you change this function to `async () => {`. It is already async so it will complete after last `await`.

2019-02-14 13:07 UTC, harbu commented on test/integration/tracker-node-reconnect-instructions.test.js
> +    it('tracker should receive statuses from both', async (done) => {
keyword `async` not needed

2019-02-14 13:07 UTC, harbu commented on test/integration/tracker-node-reconnect-instructions.test.js
> +        otherNodes.map((node) => node._clearMaintainStreamsInterval())
There is some reliance on internals here which may cause this test to require lots of fixing in future as we change internals. I think it is OK for now but in future we might want to take a more black-box approach here or, alternatively, structure our code to allow for more fine-grain testing.

2019-02-14 16:27 UTC, mirpo commented on src/connection/WsEndpoint.js
> +                    if (ws.readyState === ws.OPEN) {
Ok

2019-02-14 16:28 UTC, mirpo commented on src/connection/WsEndpoint.js
> +                        resolve()
Not sure, it's not an error, we just can't send.

2019-02-14 16:28 UTC, mirpo commented on src/logic/Node.js
> +        const alreadyConnectedNode = [...this.streams.getAllOutboundNodes()]
?

2019-02-14 16:29 UTC, mirpo commented on test/integration/connection-limits.test.js
> +                node.setConnectionLimitsPerStream(limits.maxInBound + 1, limits.maxOutBound + 1)
Originally was not correct, we have limit 6 in code, and just need in test +1 to connect to the 7th node

2019-02-14 16:29 UTC, mirpo commented on test/integration/tracker-node-reconnect-instructions.test.js
> +    it('init tracker and nodes, tracker receives stream info', async (done) => {
Ok

2019-02-14 16:30 UTC, mirpo commented on test/integration/tracker-node-reconnect-instructions.test.js
> +    it('tracker should receive statuses from both', async (done) => {
Ok

2019-02-14 16:30 UTC, mirpo commented on test/integration/tracker-node-reconnect-instructions.test.js
> +        otherNodes.map((node) => node._clearMaintainStreamsInterval())
I didn't test it, but maybe we could remove this line at all.

2019-02-20 10:07 UTC, ptesavol requested changes

2019-02-20 10:07 UTC, ptesavol commented on src/logic/Node.js
> +        await Promise.all(nodeAddresses.map(async (nodeAddress) => {
I would consider switching the order of connecting and disconnecting nodes. Now there will momentarily be nodes who have more outgoing connections than what connection limits would allow.

2019-02-20 10:07 UTC, ptesavol commented on src/logic/Tracker.js
> +const { getPeersTopology, filterOutRandomPeer } = require('../helpers/TopologyStrategy')
I would bring these helper functions from TopologyStrategy.js back to the Tracker.js file. This way there would be a single file for those people to edit who are interested in implementing different kinds of Trackers. Another idea is that maybe the tracker to be used in an experiment could be chosen with a command line parameter so the different trackers could be easier to compare.

2019-02-20 10:07 UTC, ptesavol commented on src/logic/Tracker.js
> +                outboundNodes = filterOutRandomPeer(outboundNodes)
Here you instruct the node to disconnect one outgoing connection, but what happens to the other end? The node in the other end will also have one more connection slot available after the disconnection. What happens to this slot?

2019-02-28 13:26 UTC, merged