Extract overlay topology to own class
streamr-dev/network-old pull request #180
Opened 2019-02-22 09:05 UTC by harbu

First of all this is not yet ready. I have to
- integrate this to Tracker.js
- test it out in practice
- a few edge cases need unit test still

Just made the PR to allow @ptesavol to go further with his work and comment on the logic here.

The idea here is that on receiving a node status tracker will invoke `update()` and on node disconnect `leave()`. After both cases the tracker should invoke `formInsructions(nodeId)` to get a list of `connect` and `disconnect` instructions that need to be sent to `nodeId` as well as other nodes.

2019-02-25 09:44 UTC, mirpo approved these changes

2019-02-25 12:35 UTC, harbu commented on src/logic/OverlayTopology.js
> +                    action: 'disconnect',
Would probably be better to use terms join/leave or subscribe/unsubscribe instead of connecting and disconnecting since two nodes might share other streams as well. The ultimate decision as to whether to connect or disconnect should be that of the nodes.

2019-02-25 12:41 UTC, ptesavol requested changes
It seems that in this code the tracker is assumed to give instructions to the nodes in an imperative way, ie. "disconnect from node 24234". In the current tracker.js and node implementations, however, it is assumed that the instructions from the tracker are declarative, ie. "you should have outgoing connections to nodes: [213113,23323,53533,343434]" Both the real node and my testbench assume this declarative style. Maybe this code should be updated to follow the declarative model?

2019-02-25 12:46 UTC, harbu commented
Either way is fine by me. Do you think we should be able to differentiate the active participant in these cases though, i.e., who should open the socket and who should close the socket? Or should both participants try to do it, with the one succeeding who gets to it first?

2019-02-25 12:52 UTC, ptesavol commented
I think it is better to use the declarative style because it is already implemented in the real node and the testbench. Also the active participant should be the node on the outgoing connections side. The declarations for incoming connections currently are for information only, but this feature could be used later to block incoming connections from random peers not approved by the tracker.

2019-02-25 12:54 UTC, harbu commented
Alrighty, I will look into turning this to declarative style. Hopefully done today.

2019-02-26 09:40 UTC, harbu commented
Instructions are now in declarative style

2019-02-27 11:54 UTC, merged