Ovelay topology integration with network + other stuff
streamr-dev/network-old pull request #191
Opened 2019-03-05 09:33 UTC by harbu

There are multiple things included here (stuff sort of snowballed)

1. Replace STREAM_INFO with INSTRUCTION.
2. Remove stream connection limits
3. Fix bug in duplicate socket closing
4. Integrate Tracker with OverlayTopology
5. Made errors in `PeerBook` into their own class `NotFoundInPeerBookError`
6. Fix tests

Currently there is a bit of a hack included where Tracker has a "limit" on the amount of instructions it can send to nodes. Originally I thought this was due to an inherent instability in our tracker algorithm. Now after finding the bug (_3. Fix bug in duplicate socket closing_) I think that is causing the issue. Hence, I'm now looking into removing this "limit" hack.

2019-03-05 14:07 UTC, mirpo requested changes
Looks good  :+1:

2019-03-05 14:07 UTC, mirpo commented on src/connection/WsEndpoint.js
> +            if (reason === 'streamr:endpoint:duplicate-connection') {
Move to disconnectionReasons

2019-03-05 14:07 UTC, mirpo commented on src/logic/Tracker.js
> +const NEIGHBORS_PER_NODE = 4
We need some function to change it

2019-03-05 14:07 UTC, mirpo commented on test/integration/tracker-node-reconnect-instructions.test.js
>  const { callbackToPromise } = require('../../src/util')
Maybe we need more tests for instructions here? Form instructions, send them, check connections and etc

2019-03-05 18:27 UTC, mirpo commented on src/logic/OverlayTopology.js
> +        if (this.nodes[nodeId] != null) {
Add this plz at the end (and remove module.exports in top)

if (typeof module !== 'undefined' && module.exports) {
    module.exports = OverlayTopology
}

so we'll be able to reuse in browser

2019-03-06 11:47 UTC, harbu commented on src/connection/WsEndpoint.js
> +            if (reason === 'streamr:endpoint:duplicate-connection') {
done

2019-03-06 11:51 UTC, harbu commented on src/logic/Tracker.js
> +const NEIGHBORS_PER_NODE = 4
Let's add it when the need comes?

2019-03-06 11:55 UTC, harbu commented on test/integration/tracker-node-reconnect-instructions.test.js
>  const { callbackToPromise } = require('../../src/util')
Not doing this now. I created issue for this https://github.com/streamr-dev/network/issues/192 when time.

2019-03-06 12:00 UTC, harbu commented on src/logic/OverlayTopology.js
> +        if (this.nodes[nodeId] != null) {
done

2019-03-06 12:23 UTC, merged