Storage node registration in tracker
streamr-dev/network-old pull request #232
Opened 2019-04-09 12:27 UTC by mirpo

2019-04-09 14:22 UTC, harbu requested changes
Overall looks good. I have some nitpicks and then a more bigger question about the `_formAndSendInstructionsToStorages` method.

2019-04-09 14:22 UTC, harbu commented on src/logic/Node.js
> +        if (this.protocols.nodeToNode.isStorage()) {
Wonder if we could remove this `if` so that tracker can assign any node to a stream? Up to tracker to determine logic?

2019-04-09 14:22 UTC, harbu commented on src/logic/OverlayTopology.js
> +        return this.shuffleArray(Object.keys(this.nodes)).slice(0, 1)[0]
Btw there is also
```js
return this.pickRandomElement(Object.keys(this.nodes))
```

2019-04-09 14:22 UTC, harbu commented on src/logic/Tracker.js
> +        this.storages = new Map()
I think this can get confused with `Storage` interface in Node. What about name `storageNodes` to make it perfectly clear?

2019-04-09 14:22 UTC, harbu commented on src/logic/Tracker.js
> +        if (nodeType === nodeTypes.STORAGE) {
I think this `if` is not strictly needed. `Map#delete(element)` will not fail if element does not exist In Map.

2019-04-09 14:22 UTC, harbu commented on src/protocol/PeerBook.js
> +const nodeTypes = Object.freeze({
Rename `peerTypes` for consistency?

2019-04-09 14:22 UTC, harbu commented on src/protocol/PeerBook.js
> +        return this.getTypeById(peerId) === nodeTypes.NODE
Should we also check for `STORAGE` here since storage nodes are also nodes?
I.e.
```js
return this.getTypeById(peerId) === nodeTypes.NODE || isStorage(peerId) 
```

2019-04-09 14:22 UTC, harbu commented on src/protocol/TrackerServer.js
> +                this.emit(events.NODE_STATUS_RECEIVED, {
Because of lack of typing in JavaScript, I would prefer keeping `statusMessage` name here because it is more clear what the type of the message is. Especially in tests below.

2019-04-09 14:22 UTC, harbu commented on src/logic/Tracker.js
> +                const alreadyConnected = Object.keys(status.streams)
What about re-naming to `alreadySubscribedStreams` etc. for consistency with variables `existingStreams` and `streamsToSubscribe`?

2019-04-09 14:22 UTC, harbu commented on src/logic/Tracker.js
> +            }, this)
No need for `this` with arrow function?

2019-04-09 14:22 UTC, harbu commented on src/logic/Tracker.js
> +                if (streamsToSubscribe.length) {
No need for `if` since `forEach` will not do anything if array is empty.

2019-04-09 14:22 UTC, harbu commented on src/logic/Tracker.js
> +        this._formAndSendInstructionsToStorages()
Btw is it necessary do it for all storage nodes at this point or just the storage node that sent status?

2019-04-09 14:22 UTC, harbu commented on test/integration/storage-node.test.js
> +describe('Check tracker will subscribe storage to all streams', () => {
`storage` => `storage node` in description

2019-04-09 14:22 UTC, harbu commented on src/logic/Tracker.js
> +        this._formAndSendInstructionsToStorages()
Answer to my own question: _it is necessary_ for any new streams that a non-storage node could register to Tracker via `_updateNode`.

2019-04-09 14:22 UTC, harbu commented on test/integration/storage-node.test.js
> +
Maybe add some `await` in between to make sure subscriberOne and subscriberTwo are registered before storageNode.

2019-04-09 14:22 UTC, harbu commented on test/integration/storage-node.test.js
> +        await storageNode.addBootstrapTracker(tracker.getAddress())
Btw `await` is not needed with `addBootstrapTracker` since it no longer returns promise or is async.

2019-04-09 14:22 UTC, harbu commented on test/integration/storage-node.test.js
> +        let instuctionsReceived = 0
instuctions => instructions, missing r between

2019-04-09 14:22 UTC, harbu commented on test/integration/storage-node.test.js
> +            if (streamId.key() === 'stream-1::0') {
I thinks these checks are not strictly necessary because the assertions of `getAllNodesForStream` below are also derived from addresses in protocol layer.

2019-04-10 06:47 UTC, mirpo commented on test/integration/storage-node.test.js
> +
Good point 👍

2019-04-10 07:24 UTC, mirpo commented on src/logic/Node.js
> +        if (this.protocols.nodeToNode.isStorage()) {
Hmmm, I tested. It works without this if, now I'm trying to image any situation which will break code. Removed for now.

2019-04-10 13:59 UTC, harbu commented on src/protocol/PeerBook.js
> +        return this.getTypeById(peerId) === nodeTypes.NODE
@mirpo what about this one?

2019-04-10 14:06 UTC, harbu approved these changes

2019-04-10 14:10 UTC, merged