Use streamr client protocol js
streamr-dev/network-old pull request #279
Opened 2019-06-07 08:55 UTC by mthambipillai

This PR replaces the existing protocol implementation for the Control Layer and the Message Layer with the protocol implementation used in the centralised network and defined [here](https://github.com/streamr-dev/streamr-client-protocol-js).

2019-06-07 09:26 UTC, mirpo requested changes
LGFM 👍

2019-06-07 09:26 UTC, mirpo commented on .idea/runConfigurations/integration_test.xml
> +    <node-interpreter value="$USER_HOME$/.nvm/versions/node/v10.12.0/bin/node" />
Not sure, is it needed?

2019-06-07 09:26 UTC, mirpo commented on .idea/runConfigurations/test.xml
> +    <node-interpreter value="$USER_HOME$/.nvm/versions/node/v10.12.0/bin/node" />
The same

2019-06-07 09:26 UTC, mirpo commented on src/logic/Node.js
> +        if (!this.streams.isSetUp(streamId, streamId)) {
isSetUp - takes only one parameter

2019-06-07 09:26 UTC, mirpo commented on src/logic/Node.js
> +            this.streams.setUpStream(streamId, streamId)
setUpStream - takes only one parameter

2019-06-07 09:26 UTC, mirpo commented on src/logic/Node.js
> +    onDataReceived(streamMessage, source = null) {
Is it possible that source could be null? @harbu

2019-06-07 09:44 UTC, mirpo commented
One point about bringing JS protocol into network, I don't like idea of removing "source" from messages. Each message in network supposed to have a source, so it is atomic structure - "message + source".
So I think it's better to add Network implementation of each message in protocol (aka extend and add fields) or extend each message class in network project.

2019-06-10 12:58 UTC, harbu requested changes
LGTM; I added some comments of potential things I found + a few questsions + a few discussion topics for network meeting.

2019-06-10 12:58 UTC, harbu commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_6" default="false" project-jdk-name="1.8" project-jdk-type="JavaSDK" />
Are these project file changes purposeful?

2019-06-10 12:58 UTC, harbu commented on src/NetworkNode.js
>          signature,
Might be worth changing the API of publish so that `signatureType` is before `signature` for consistency.

2019-06-10 12:58 UTC, harbu commented on src/NetworkNode.js
>  function unicastMessageToObject(unicastMessage) {
Let's discuss in next meeting whether we want to evolve this API to directly return streamr-client-protocol-js messages, or is the current just plain objects solution fine.

2019-06-10 12:58 UTC, harbu commented on src/helpers/MessageEncoder.js
> +    if (code === undefined) {
Do we need a _protocol layer_ in our network anymore? Or is `streamr-client-protocol-js` basically the protocol layer. Let's discuss in next meeting.

2019-06-10 12:58 UTC, harbu commented on src/logic/Node.js
> +    onDataReceived(streamMessage, source = null) {
It is `null` when the data is being published locally.

2019-06-10 12:58 UTC, harbu commented on src/logic/Node.js
> +            this.messageBuffer.put(`${streamMessage.getStreamId()}::${streamMessage.getStreamPartition()}`, [streamMessage, source])
You can use `streamIdAndPartition.key()` to avoid repeating the key forming logic.

2019-06-10 12:58 UTC, harbu commented on src/logic/Node.js
> +                streamMessage.m, MIN_NUM_OF_OUTBOUND_NODES_FOR_PROPAGATION)
`streamMessage.messageId` ?

2019-06-10 12:58 UTC, harbu commented on src/logic/Node.js
> +            this.messageBuffer.put(`${streamMessage.getStreamId()}::${streamMessage.getStreamPartition()}`, [streamMessage, source])
Same point as before regarding `key()` method

2019-06-10 12:58 UTC, harbu commented on src/protocol/NodeToNode.js
> +    sendUnsubscribe(receiverNodeId, streamIdAndPartition) {
Just a thought: would it be worth renaming the `StreamId` class to `StreamIdAndPartition`? It would be more line in with the naming convention going on in this PR's change set.

2019-06-10 12:58 UTC, harbu commented on src/protocol/NodeToNode.js
> +    send(receiverNodeId, message) {
👍

2019-06-10 12:58 UTC, harbu commented on src/protocol/TrackerNode.js
> +        // Unifying all the messages in the same protocol with a third layer would allow to avoid this hack
Not sure I understand this part. Why do we return on `message.version === 1`? Is it to prevent node-to-node messages from getting handled?

2019-06-10 12:58 UTC, harbu commented on test/integration/storage-node.test.js
> +        expect(subscriberOne.streams.isSetUp(streamOne, streamOne)).toBeFalsy()
two arguments?

2019-06-10 13:19 UTC, harbu commented
> One point about bringing JS protocol into network, I don't like idea of removing "source" from messages. Each message in network supposed to have a source, so it is atomic structure - "message + source".
> So I think it's better to add Network implementation of each message in protocol (aka extend and add fields) or extend each message class in network project.

We could have some sort of a wrapper, e.g.,
```js
class WrappedMessage {
   constructor(msg, source) {
      this.msg = msg
      this.source = source
   }
}
```

Though a more lightweight (and perhaps a bit less 'Javaish' solution) would be to just pass objects
```js
{
   msg: msg,
   source: 'sourceId'
}
```

In this PR we pass arrays that have a positional interpretation
```js
[msg, source]
```

I think a shortcoming here is that we don't have a type system in use. That would catch situations where I'm trying to, e.g.,

```js 
const [sourceId, msg] = xxx
doSomething(msg.streamId)
```

even though it should be
```js
const [msg, source] = xxx
doSomething(msg.streamId)
```

2019-06-10 13:48 UTC, mthambipillai commented on src/helpers/MessageEncoder.js
> +    if (code === undefined) {
Yes it's still needed for messages that are not in `streamr-client-protocol-js`. This is why I was suggesting to add a third layer in the last meeting.

2019-06-10 13:51 UTC, mthambipillai commented on src/protocol/TrackerNode.js
> +        // Unifying all the messages in the same protocol with a third layer would allow to avoid this hack
Yes this is the reason. This is why in the last meeting I was suggesting a third layer with a new message like "NodeToNodeMessage" that would encapsulate Control Layer payloads and some node specific info (like the source). It seems like your comment below suggests the same thing

2019-06-20 14:45 UTC, harbu commented
I checked new commits. Looks good to me. Only thing I would still like to see is tests for new wrapper message type in
- test/unit/encoder.test.js
- test/integration/delivery-of-messages-protocol-layer.test.js (if applicable)

2019-06-26 07:15 UTC, mthambipillai commented
Added unit tests in `encoder.test.js`. Didn't add tests in `delivery-of-messages-protocol-layer.test.js` since there already are tests for every possible payload of the WrapperMessage.

2019-06-26 07:16 UTC, merged