Add process cpu and memory usage metrics
streamr-dev/network-old pull request #287
Opened 2019-07-03 11:08 UTC by mirpo

2019-07-05 08:38 UTC, harbu requested changes

2019-07-05 08:38 UTC, harbu commented on src/metrics.js
> +        const stats = await this.pidusage(pid)
Why set `this.pidusage = pidusage` and not just use directly `pidusage(pid)` ?

2019-07-05 08:38 UTC, harbu commented on src/logic/Node.js
> +        metrics.pidMetrics = await this.metrics.getPidusage()
Maybe move this line inside`Metrics#report()`. That way also tracker will report pid usage.

2019-07-09 09:15 UTC, mirpo commented on src/metrics.js
> +        const stats = await this.pidusage(pid)
👍

2019-07-09 09:15 UTC, mirpo commented on src/logic/Node.js
> +        metrics.pidMetrics = await this.metrics.getPidusage()
👍

2019-07-09 11:30 UTC, harbu approved these changes

2019-07-09 12:37 UTC, merged