Remove not needed interfaces
streamr-dev/network-old pull request #296
Opened 2019-07-17 08:59 UTC by mirpo

fixes #291

2019-07-17 11:32 UTC, harbu requested changes

2019-07-17 11:32 UTC, harbu commented on test/integration/tracker-node-status.test.js
> +        tracker.protocols.trackerServer.once(TrackerServer.events.NODE_STATUS_RECEIVED, ({ statusMessage, _ }) => {
You can leave out underscore.

2019-07-17 11:32 UTC, harbu commented on test/integration/tracker-node-status.test.js
> +        tracker.protocols.trackerServer.once(TrackerServer.events.NODE_STATUS_RECEIVED, ({ statusMessage, _ }) => {
You can leave out underscore.

2019-07-17 11:32 UTC, harbu commented on test/integration/tracker-node-status.test.js
> +            tracker.protocols.trackerServer.on(TrackerServer.events.NODE_STATUS_RECEIVED, ({ statusMessage, _ }) => {
You can leave out underscore.

2019-07-17 11:32 UTC, harbu commented on test/integration/tracker-node-reconnect-instructions.test.js
> +        tracker.protocols.trackerServer.on(TrackerServer.events.NODE_STATUS_RECEIVED, ({ statusMessage, _ }) => {
You can leave out underscore.

2019-07-17 11:32 UTC, harbu commented on test/integration/tracker-node-reconnect-instructions.test.js
> +        otherNodes[1].protocols.nodeToNode.endpoint.once(events.PEER_DISCONNECTED, ({ _, reason }) => {
You can leave out underscore.

2019-07-18 07:41 UTC, mirpo commented
moved to #299

2019-07-18 07:41 UTC, closed without merging