Devops 121 docker dev
streamr-dev/network-old pull request #331
Opened 2019-09-20 12:40 UTC by mthambipillai

Notes:
- The Dockerfile is actually only for the tracker
- I had to remove the host param when creating the WebSocket server so that it would be accessible from outside the Docker container

2019-09-23 06:10 UTC, mirpo requested changes

2019-09-23 06:10 UTC, mirpo commented on .travis_scripts/deploy_docker.sh
> +    #docker tag $OWNER/$IMAGE_NAME:$TAG $OWNER/$IMAGE_NAME:$TRAVIS_TAG
Please remove commented lines.

2019-09-23 06:10 UTC, mirpo commented on Dockerfile
> +FROM node:8.11.4-alpine
We use node 10

2019-09-23 06:10 UTC, mirpo commented on bin/tracker.js
> +const ip = process.argv[3]
We use it ./bin/ scripts, they might fail now, better run them to recheck

2019-09-23 11:29 UTC, mthambipillai commented on bin/tracker.js
> +const ip = process.argv[3]
Ran them locally, none fails

2019-09-23 12:03 UTC, mirpo approved these changes

2019-09-24 10:02 UTC, mirpo commented
LGFM!

2019-09-24 11:00 UTC, merged