NET-60: cleanup README
streamr-dev/network-old pull request #338
Opened 2019-10-03 10:47 UTC by harbu

2019-10-03 14:28 UTC, hpihkala requested changes
A few thoughts while reading

2019-10-03 14:28 UTC, hpihkala commented on README.md
Can't comment on the correct line (38), but the `Screenshot of the demo running` URL is broken (404). Is the `network-runner` useful, maintained, and up to date? Or should we remove that liability by removing the Demo section from here?

2019-10-03 14:28 UTC, hpihkala commented on README.md
> +[Streamr protocol](https://github.com/streamr-dev/streamr-client-protocol-js) written in Node.js.
(voices in my head: do we want to rule out browsers? is node.js a language?)
```suggestion
[Streamr protocol](https://github.com/streamr-dev/streamr-client-protocol-js) in JS.
```

2019-10-03 14:28 UTC, hpihkala commented on README.md
> +[Streamr protocol](https://github.com/streamr-dev/streamr-client-protocol-js) written in Node.js.
Would it be better to link to protocol spec instead of JS impl?
```suggestion
[Streamr protocol](https://github.com/streamr-dev/streamr-specs/blob/master/PROTOCOL.md) written in Node.js.
```

2019-10-03 14:28 UTC, hpihkala commented on README.md
> +This repository/package contains an extendable server-side implementation of the
Only server-side? I guess it could work for clients too? (ofc not tested in browsers yet though)

2019-10-03 14:28 UTC, hpihkala commented on README.md
>  Integration into existing project could be found in [Examples](./examples)
This line has some language problems, and it's unclear what "Integration into existing project" means. If the point is to point the reader to the Examples, I recommend changing the title to `Examples` and then rewriting the description what can be found there.

2019-10-03 14:28 UTC, hpihkala commented on README.md
>  ## Examples
Oh alright, here we have the Examples title, so the above Integrations can maybe be completely removed (don't need two sections that both point to the `examples` folder). The content here is ultra-brief, needs expansion. What kind of examples can be found there? What/who are they useful for?

2019-10-03 14:28 UTC, hpihkala commented on README.md
> +Run an example network locally (10 nodes):
Ah nice! If this is so easy, then the `network-runner` demo at the top is unnecessary?

2019-10-06 06:18 UTC, harbu commented on README.md
Removed demo section

2019-10-06 06:18 UTC, harbu commented on README.md
> +[Streamr protocol](https://github.com/streamr-dev/streamr-client-protocol-js) written in Node.js.
Fixed

2019-10-06 06:18 UTC, harbu commented on README.md
> +This repository/package contains an extendable server-side implementation of the
A bit hard to define. It's not purely server but yeah not a "light client" either. Anyways, removed term "server-side".

2019-10-06 06:19 UTC, harbu commented on README.md
>  Integration into existing project could be found in [Examples](./examples)
Removed this paragraph.

2019-10-06 06:20 UTC, harbu commented on README.md
>  ## Examples
Re-did writing of Examples section.

2019-10-06 07:26 UTC, merged