Add draft unit and integration tests, code coverage is around 75%
streamr-dev/network-old pull request #38
Opened 2018-09-12 08:31 UTC by mirpo

fixes #14

2018-09-12 13:30 UTC, harbu requested changes
Looking good! Couple changes.

* Need async connections
* Multiple ports  for trackers so can be run concurrently
* Disconnection issue?

2018-09-12 13:30 UTC, harbu commented on publisher-libp2p.js
> +        if (publisher.connection.isStarted()) {
Need to use new async connection here.

2018-09-12 13:30 UTC, harbu commented on publisher.js
> +        if (publisher.connection.isStarted()) {
Need to use new async connection here.

2018-09-12 13:30 UTC, harbu commented on src/connection/Connection.js
> +    isStarted() {
I think this can be removed.

2018-09-12 13:30 UTC, harbu commented on src/protocol/TrackerNode.js
> +            await this.connection.connect(tracker).catch((err) => {
Does catch also get invoked when `resolve` is invoked inside Promise? I thought it only gets invoked when `reject` is invoked?

2018-09-12 13:30 UTC, harbu commented on test/integration/connection.test.js
> +        const connection = new Connection('127.0.0.1', 30337)
async connection creation

2018-09-12 13:30 UTC, harbu commented on test/integration/publisher.test.js
> +        const connection = new Connection('127.0.0.1', 30333, '', true)
async connection

2018-09-12 13:30 UTC, harbu commented on test/integration/tracker.test.js
> +        const connection = new Connection('127.0.0.1', 30300, PRIVATE_KEY)
async connection

2018-09-12 13:30 UTC, harbu commented on test/unit/connection.test.js
> +        connection.on('node:ready', () => {
async connection

2018-09-12 13:30 UTC, harbu commented on test/unit/encoder.test.js
> +        assert.equal(encoder.STATUS, 0)
IMO this level of testing is not necessary. It is obvious from code what the values are.

2018-09-12 13:30 UTC, harbu commented on test/unit/encoder.test.js
> +        const json = encoder.streamMessage('stream-address', 'node-address')
Can we use `stream-id` instead of `stream-address`.

2018-09-13 12:41 UTC, mirpo commented on test/unit/encoder.test.js
> +        const json = encoder.streamMessage('stream-address', 'node-address')
Sure

2018-09-13 13:18 UTC, harbu commented
LGTM, but we should make Travis pass. Currently not liking ESLint 😆

2018-09-13 13:19 UTC, harbu approved these changes

2018-09-13 13:19 UTC, harbu commented on src/connection/Connection.js
> +        return new Promise((resolve, reject) => this.node.stop((err) => (err ? reject(err) : resolve(callback))))
Good one! I actually need this in broker. 💯

2018-09-13 13:22 UTC, merged