WebRTC
streamr-dev/network-old pull request #385
Opened 2020-01-31 10:30 UTC by harbu

2020-01-31 12:44 UTC, ptesavol commented on src/connection/WebRtcEndpoint.js
> +            if (connection) {
This seems to only work if the receiver of the offer has already called connect(), which is not always the case. I thin it would be best to move the creation of the RTCPeerConnection to a helper function that is called from both connect() and from here if connect() has not been called yet.

2020-01-31 12:49 UTC, ptesavol commented on src/connection/WebRtcEndpoint.js
> +        connection.onnegotiationneeded = (event) => {
It is best to start creating the offer in this onnegotiationneeded callback. This gets fired whenever new data channel is added to the RTCPeerConnection and when network connection settings change in some way or another (ie. reconnect after short disconnection)

2020-01-31 12:55 UTC, ptesavol commented on src/connection/WebRtcEndpoint.js
> +            this._initDataChannel(targetPeerId, connection.createDataChannel())
here you can set whether you want the dataChannel to be reliable of not, and give a name to the data channel like this: 

let channel = connection.createDataChannel("jsonrpcchannel", { reliable: true });

it is also a good idea to set the binary type to arraybuffer here, in case we will transmit binary data at some point:

channel.binaryType = "arraybuffer";

2020-01-31 13:19 UTC, harbu commented on src/connection/WebRtcEndpoint.js
> +            this._initDataChannel(targetPeerId, connection.createDataChannel())
Looks like the data channel negotiation can be mode symmetrical in the code by using `negotiated: true` option. Then both ends just call `createDataChannel` see: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel#Examples

I wonder if there is any downsides to enabling this?

2020-01-31 13:21 UTC, harbu commented on src/connection/WebRtcEndpoint.js
> +            this._initDataChannel(targetPeerId, connection.createDataChannel())
I guess both parties need to know the `channelId` beforehand for this approach to work. If we just use one channel to transmit data this should be easy. If, however, we wanted to use a channel per stream approach we need negotiation.

2020-01-31 13:25 UTC, harbu commented on src/connection/WebRtcEndpoint.js
> +            if (connection) {
Good point. I'll make a test for this case and then fix it to work when the receiver has not yet invoked `connect`.

2020-02-03 14:11 UTC, harbu commented on src/connection/WebRtcEndpoint.js
> +        connection.onnegotiationneeded = (event) => {
done

2020-02-10 07:32 UTC, mirpo requested changes
LGFM, commander!
What we are going to do with WS endpoint? remove it at all? or keep?

2020-02-10 07:32 UTC, mirpo commented on src/connection/WebRtcEndpoint.js
> +            negotiated: true
Did you discuss other flags?
```
ordered: If the data channel should guarantee order or not
maxPacketLifeTime: The maximum time to try and retransmit a failed message
maxRetransmits: The maximum number of times to try and retransmit a failed message
```

2020-02-10 07:32 UTC, mirpo commented on src/connection/WebRtcEndpoint.js
> +            id: 0,
why zero and not some `uuid`?

2020-02-10 07:32 UTC, mirpo commented on src/connection/WebRtcEndpoint.js
> +        const isOffering = this.id < targetPeerId
why do we need this isOffering?

2020-02-10 07:32 UTC, mirpo commented on src/connection/WebRtcEndpoint.js
> +            console.log('onconnectionstatechange', this.id, connection.connectionState, event)
`connectionState` 🥇

2020-02-10 07:32 UTC, mirpo commented on src/connection/WebRtcEndpoint.js
> +            console.error(event)
maybe we need here `this.emit(events.PEER_DISCONNECTED, targetPeerId)`

2020-02-10 07:32 UTC, mirpo commented on src/connection/WebRtcEndpoint.js
> +            console.error(event)
And I don't see where you remove connections from `this.connections` and do some `.close()`

2020-02-10 07:32 UTC, mirpo commented on src/logic/RtcSignaller.js
> +        this.offerListener = fn
`fn` - arghhh

2020-02-10 07:32 UTC, mirpo commented on src/protocol/TrackerNode.js
> +    sendRtcOffer(trackerId, targetNode, originatorNode, data) {
I think it's better to remove `originatorNode` from parameters, it's just internal info from endpoint

2020-02-10 07:32 UTC, mirpo commented on test/unit/WebRtcEndpoint.test.js
> +        endpoint1 = new WebRtcEndpoint('node-1', ['stun:stun.l.google.com:19302'], new RtcSignaller('node-1', trackerNode1))
later we'll need smth like https://www.npmjs.com/package/stunsrv

2020-02-10 07:32 UTC, mirpo commented on test/unit/WebRtcEndpoint.test.js
> +        await waitForCondition(() => ep1NumOfReceivedMessages > 9)
ep1NumOfReceivedMessages == 10 ?

2020-02-14 09:19 UTC, harbu commented on src/connection/WebRtcEndpoint.js
> +            negotiated: true
Good thing about WebRTC is that these are quite easy to change in future. I'd go with defaults now unless we have a reason to change something.

2020-02-14 09:22 UTC, harbu commented on src/connection/WebRtcEndpoint.js
> +            id: 0,
Both sides must agree on id beforehand when using "out-of-band" data channels. Stackoverflow answer here https://stackoverflow.com/questions/43788872/how-are-data-channels-negotiated-between-two-peers-with-webrtc provides more insight into the two different modes of data channel setup. Basically for a fixed amount of data channels (we have one now) it is better to use out-of-band negotiation.

2020-02-14 10:03 UTC, harbu commented on src/connection/WebRtcEndpoint.js
> +        const isOffering = this.id < targetPeerId
WebRTC doesn't work if both sides try to send offer to each other at same time. Because `tracker` currently sends instruction to both participants to connect to each other, I added this check to ensure that only one side sends offer and the other answers. I could actually add a comment here to explain this. Later on we may want to change tracker to send connection instruction to only one participant, perhaps, needs further discussion.

2020-02-14 10:03 UTC, harbu commented on src/connection/WebRtcEndpoint.js
> +            console.log('onconnectionstatechange', this.id, connection.connectionState, event)
Hopefully not as problematic as readyState...

2020-02-14 12:41 UTC, harbu commented on test/unit/WebRtcEndpoint.test.js
> +        await waitForCondition(() => ep1NumOfReceivedMessages > 9)
fixed

2020-03-18 08:52 UTC, mirpo commented on src/connection/WebRtcEndpoint.js
> +                        }, 100)
real time? :)

2020-03-18 09:02 UTC, mirpo commented on src/logic/Node.js
> +            await this.protocols.nodeToNode.connectToNode(nodeId, tracker)
you need to update all this logic from master

2020-03-18 09:06 UTC, mirpo commented on test/integration/tracker-node-reconnect-instructions.test.js
>              firstCheck = true
why you removed `NO_SHARED_STREAMS` ?

2020-03-18 09:08 UTC, mirpo approved these changes
LGFM

2020-03-18 09:08 UTC, mirpo commented on test/integration/unsubscribe-from-stream.test.js
>          nodeB.unsubscribe('s', 2)
maybe we can await for some condition?

2020-05-26 14:49 UTC, juslesan commented on src/connection/WebRtcEndpoint.js
> +        connection.oniceconnectionstatechange = (event) => {
If connection is set to failed it seems that it is never repaired, causing the network to break. It seems that in some cases the other end of the connection will disconnect if the state is set to failed, but the connection is never re-established.

2020-06-16 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/streamr-dev/network?pullRequest=385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/streamr-dev/network?pullRequest=385) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: harbu<br/>:x: juslesan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/streamr-dev/network?pullRequest=385) it.</sub>

2020-11-26 10:04 UTC, harbu commented
Closed. We went with `node-datachannel` library instead of `wrtc`.

2020-11-26 10:04 UTC, closed without merging