Fix ws endpoint crashing
streamr-dev/network-old pull request #387
Opened 2020-02-14 06:15 UTC by mirpo

2020-02-14 08:28 UTC, juslesan approved these changes

2020-02-14 09:17 UTC, harbu requested changes
LGTM; but I think the tests should be moved to a different place

2020-02-14 09:17 UTC, harbu commented on test/unit/tracker.test.js
> +    it('tracker must check all required information for new incoming connection and not crash', async () => {
This is testing functionality of `WsEndpoint` right? Should these tests be in 'ws-endpoint.test.js' or some new test file dedicated to WsEndpoint?

2020-02-17 02:55 UTC, mirpo commented on test/unit/tracker.test.js
> +    it('tracker must check all required information for new incoming connection and not crash', async () => {
Soon only tracker will use websocket

2020-02-17 09:20 UTC, harbu approved these changes

2020-02-17 09:23 UTC, merged