Update fork of uws with latest uWebsocket.js
streamr-dev/network-old pull request #392
Opened 2020-02-27 08:26 UTC by mirpo

2020-03-02 11:30 UTC, juslesan approved these changes

2020-03-03 10:17 UTC, harbu requested changes

2020-03-03 10:17 UTC, harbu commented on package.json
> +    "ws": "^7.2.1"
Should we remove `ws` from `devDependencies`?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +    if (ws.terminate !== undefined) {
Should this be `ws.close !== undefined` ?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +        this.wss.get('/', (res, req) => {
Do I understand correctly that an additional HTTP forwarding step is involved when connecting to a node?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +                    this.emit('close', ws, code, reason) // event for back compatibility
What is this `close` event? Is the intention to emit this event on the `wss` object? If yes, then I think it should be `this.wss.emit`.

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +        setImmediate(() => this.emit(events.MESSAGE_RECEIVED, peerInfo, message))
Why the addition of `setImmediate`?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +                    const peerId = res.headers['streamr-peer-id']
Case sensitivity?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
>                          reject(new Error('dropping outgoing connection because upgrade event never received'))
I'm guessing we should use some other term than upgrade here so we don't confuse with the upgrade mechanism of HTTP -> Socket of WebSocket?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +            try {
Out of curiosity: why Promise instead of async/await?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +            this.emit('connection', ws) // event for back compatibility
What is this `connection` event? Is the intention to emit this event on the `wss` object? If yes, then I think it should be `this.wss.emit`.

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +            this.metrics.inc('_onIncomingConnection:closed:no-required-parameter')
missing is a more accurate word here since some of the parameters may be present

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +    _onNewConnection(ws, address, peerInfo, out = true) {
Do we need parameters `address` and `peerInfo` since they are already found within "user data" of `ws`? (I.e. `ws.peerInfo` and `ws.address`)

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +        // thereby leaving no connection behind.g
typo

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +            closeWs(ws, 1002, e.toString())
Removed `disconnectionCodes.MISSING_REQUIRED_PARAMETER` on purpose?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +            closeWs(ws, 1000, disconnectionReasons.DUPLICATE_SOCKET)
`disconnectionCodes.DUPLICATE_SOCKET`?

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +    _onNewConnection(ws, address, peerInfo, out = true) {
I don't think boolean parameter `out` has a "natural" default value that one could expect it to take without having to read the method signature. Thus I'd prefer we supply the value of the argument every time we call this function.

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +        return peerInfo
Maybe just `return true` if we only need return value for checking for success.

2020-03-03 10:17 UTC, harbu commented on src/connection/WsEndpoint.js
> +                resolve([server, token])
Should `token` be re-named `listenSocket`? Token sounds like some string/number.

2020-03-03 10:17 UTC, harbu commented on src/logic/Node.js
> +        if (nodeAddresses.length) {
If tracker sends us an empty list of nodeAddresses it means we should unsubscribe from all nodes. Thus I don't think it is correct to skip.

2020-03-03 10:17 UTC, harbu commented on src/logic/Node.js
> -        this._disconnectFromAllNodes()
Why are these removed? Shouldn't we disconnect when we stop Node?

2020-03-03 10:17 UTC, harbu commented on src/logic/Tracker.js
> +                    this.protocols.trackerServer.sendInstruction(nodeId, StreamIdAndPartition.fromKey(streamKey), newNeighbors)
Some background info on why this change?

2020-03-03 10:17 UTC, harbu commented on src/logic/Tracker.js
>                  } catch (e) {
Dunno if this catch is useful anymore since an error will not be thrown on failure of delivery.

2020-03-03 10:17 UTC, harbu commented on src/logic/Tracker.js
>                          } catch (e) {
Again, this catch is not gonna be really invoked  ever with `sendSync`.

2020-03-03 10:17 UTC, harbu commented on src/protocol/TrackerServer.js
> +        this.endpoint.sendSync(receiverNodeId, encoder.instructionMessage(streamId, listOfNodeAddresses))
Btw what is difference between `sendSync` and `send`. Can we just move to use one of them?

2020-03-03 10:17 UTC, harbu commented on test/integration/duplicate-connections-are-closed.test.js
> +    let ws1
Unused vars

2020-03-03 10:17 UTC, harbu commented on test/integration/duplicate-connections-are-closed.test.js
>          // TODO enable later
This todo can be removed I think

2020-03-03 10:17 UTC, harbu commented on test/integration/tracker-assigns-storage-to-empty-stream.test.js
> +        await Promise.all([
Even though awaiting promises sequentially is slightly slower, I find that it better for debugging because you can put breakpoints on individual await lines and see which one exactly is causing the problem.

2020-03-03 10:17 UTC, harbu commented on test/integration/tracker-assigns-storage-node-to-streams.test.js
> +        await Promise.all([
Even though awaiting promises sequentially is slightly slower, I find that it better for debugging because you can put breakpoints on individual await lines and see which one exactly is causing the problem.

2020-03-03 10:17 UTC, harbu commented on test/integration/l1-resend-requests.test.js
> +            'requestId2',
Probably not needed since new contactNode started before each test?

2020-03-03 10:17 UTC, harbu commented on test/integration/l1-resend-requests.test.js
> +            'requestId3',
Same as above

2020-03-03 10:17 UTC, harbu commented on test/integration/l1-resend-requests.test.js
> +        const stream = contactNode.requestResendLast('streamId', 0, 'requestId1', 10)
Prolly can keep original `requestId` since contactNode is now re-instantiated before each test.

2020-03-03 10:17 UTC, harbu commented on test/integration/l3-resend-requests.test.js
> -    beforeEach(() => {
Actually this is needed otherwise we are testing L2. That being said, I found a more deterministic way to do it in WebRTC  branch. Maybe add same thing here?
https://github.com/streamr-dev/network/pull/385/files#diff-38a6c48b5d7654159065a03ee5236c20R109-R114

2020-03-04 06:37 UTC, mirpo commented on src/connection/WsEndpoint.js
> +    if (ws.terminate !== undefined) {
Both libs have close method, and only `ws` has terminate. So I check this method to understand which socket I currently use.

2020-03-04 06:38 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        this.wss.get('/', (res, req) => {
Yes

2020-03-04 06:39 UTC, mirpo commented on src/connection/WsEndpoint.js
> +                    this.emit('close', ws, code, reason) // event for back compatibility
uws is not child of EventEmitter.

2020-03-04 06:42 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        setImmediate(() => this.emit(events.MESSAGE_RECEIVED, peerInfo, message))
To make it more async, we already know that it helps. Check [this](https://stackoverflow.com/questions/15349733/setimmediate-vs-nexttick/15349865#15349865)

2020-03-04 06:58 UTC, mirpo commented on src/logic/Node.js
> +        if (nodeAddresses.length) {
Tracker should not send empty lists. It means that tracker is malicious or broken

2020-03-04 06:58 UTC, mirpo commented on src/logic/Node.js
> -        this._disconnectFromAllNodes()
We close all connections in endpoint.

2020-03-11 12:40 UTC, mirpo commented on src/logic/Node.js
> +        if (nodeAddresses.length) {
I'll create separate PR which will change the way we add storage into overlay.

2020-03-17 09:45 UTC, harbu commented on src/logic/Node.js
> +        if (nodeAddresses.length) {
Let N1 be a storage node and subscribed to stream S1. Let's say a new node, N2, joins and subscribes to stream S1. Now the current topology is:
```js
{
   N1: {
       S1: [N2]
   },
   N2: {
      S1: [N1]
   }
}
```

Now, if N2 unsubscribes from S1, tracker will need to send empty list to storage node N1, right?
```
{ stream: S1, nodeAddresses: [] }
```

2020-03-17 11:37 UTC, harbu approved these changes

2020-03-17 11:39 UTC, merged