Remove async in sending instructions, refactor send method
streamr-dev/network-old pull request #398
Opened 2020-03-11 13:46 UTC by mirpo

2020-03-11 15:20 UTC, harbu requested changes
Nice! See comments, I think you don't need new conditions in the if statements?

2020-03-11 15:20 UTC, harbu commented on src/connection/WsEndpoint.js
> +        if (!this.isConnected(recipientAddress) || !this.connections.has(recipientAddress)) {
But isn't `this.isConnected()` already effectively `this.connections.has`?

2020-03-11 15:20 UTC, harbu commented on src/connection/WsEndpoint.js
> +            if (!this.isConnected(recipientAddress) || !this.connections.has(recipientAddress)) {
Same as above

2020-03-12 07:53 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        if (!this.isConnected(recipientAddress) || !this.connections.has(recipientAddress)) {
Good point!

2020-03-16 07:39 UTC, harbu approved these changes

2020-03-16 07:40 UTC, merged