Fix subscribe logic, update _checkConnections
streamr-dev/network-old pull request #405
Opened 2020-03-20 10:08 UTC by mirpo

2020-03-20 12:16 UTC, juslesan approved these changes

2020-03-20 15:30 UTC, harbu requested changes
Have some questions on some of the changes and a few minor improvement ideas.

2020-03-20 15:30 UTC, harbu commented on src/connection/WsEndpoint.js
> +        //
What's this about? Should error be logged?

2020-03-20 15:30 UTC, harbu commented on src/connection/WsEndpoint.js
> +        //
What's this about? Should error be logged?

2020-03-20 15:30 UTC, harbu commented on src/connection/WsEndpoint.js
> +                terminateWs(ws)
Should we log error?

2020-03-20 15:30 UTC, harbu commented on src/connection/WsEndpoint.js
> +            if (this.isConnected(address)) {
I wonder how this interacts with the duplicate detection logic we have in method `_onNewConnection`.

2020-03-20 15:30 UTC, harbu commented on src/logic/Node.js
> +                        const node = result.value
What's the reasoning behind moving this logic here? To me it really seems that adding the inbound/outbound nodes and emitting the event belongs in the `_subscribeToStreamOnNode` method.

2020-03-20 15:30 UTC, harbu commented on test/integration/network-stabilization.test.js
> +    const nodes = []
It's better to initialise in `beforeEach` to avoid surprises in future if someone decides to add a new test case to this suite.

2020-03-20 15:30 UTC, harbu commented on test/integration/network-stabilization.test.js
> +    it('expect to _formAndSendInstructions not to be called when topology is stable', async () => {
"expect <del>to</del> _formAndSendInstructions not to be called..."

2020-03-20 15:30 UTC, harbu commented on test/integration/network-stabilization.test.js
> +        await wait(10000)
I'd suggest inserting a check that the function `_formAndSendInstructions` exists before the await, e.g.,
```js
expect(this._formAndSendInstructions).toBeInstanceOf(Function)
```

This is in case we decide to re-name the function in the future or whatever.

2020-03-20 16:40 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        //
We don't need to log this error, anyway we're closing socket

2020-03-20 16:40 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        //
We don't need to log this error, anyway we're closing socket

2020-03-20 16:40 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        //
`//` for eslint

2020-03-20 16:41 UTC, mirpo commented on src/connection/WsEndpoint.js
> +            if (this.isConnected(address)) {
We had before this logic in `verifyClient`. But `uws` doesn't have this method.

2020-03-20 16:44 UTC, mirpo commented on src/logic/Node.js
> +                        const node = result.value
I just removed duplicate code.
Because 
```
async _subscribeToStreamOnNode(node, streamId) {
        if (this.streams.hasInboundNode(streamId, node) && this.streams.hasOutboundNode(streamId, node)) {
            return node
        }

        return this.protocols.nodeToNode.sendSubscribe(node, streamId).then((nodeId) => {
            return nodeId
        })
    }
```
here we need to trigger NODE_SUBSCRIBED in both cases to propagate buffered messages

2020-03-20 16:45 UTC, mirpo commented on test/integration/network-stabilization.test.js
> +    const nodes = []
ok

2020-03-20 16:45 UTC, mirpo commented on test/integration/network-stabilization.test.js
> +        await wait(10000)
good point

2020-03-23 11:36 UTC, harbu requested changes

2020-03-23 11:36 UTC, harbu commented on src/connection/WsEndpoint.js
> +        //
I think the problem is that the catch is too wide and it could hide other errors than what was intended. For example, what if `WsEndpoint` had some bug that causes this function to be called as follows `closeWs(undefined, 101, 'lorem')` Then `ws.end()`  would throw an error (because `ws = undefined`) but this would then get hidden from us.

Maybe the intention is to do something like the following (image this was Java or C++ for a minute):
```java
try {
  ws.end()
} catch (ReadyStateException e) {
   // nop
} catch (Error e) {
    console.error(e)
}
```

I think you can do something similar in Node.js
```
try {
} catch (e) {
   if (e instance of ReadyStateError) {
   } else {
      throw e
   }
}
```

Nowadays you can also use https://nodejs.org/api/errors.html#errors_error_code I guess?

2020-03-23 11:36 UTC, harbu commented on src/connection/WsEndpoint.js
> +        //
Same comment as above

2020-03-23 11:36 UTC, harbu commented on src/connection/WsEndpoint.js
> +                terminateWs(ws)
?

2020-03-23 11:36 UTC, harbu commented on src/logic/Node.js
> +                        const node = result.value
I don't understand how this removes duplicate code. I just see the code moved from one place to another?

The way the code behaves is slightly different now, is this intentional? Whereas before it would add inbound/outboud nodes and emit event as soon as the subscribe message went through, now it will wait for subscribe messages for all nodes to go through (or to fail) via `allSettled` and only then proceed to add inbound/outbound nodes and emit events.

2020-03-23 11:36 UTC, harbu commented on src/connection/WsEndpoint.js
> +            if (this.isConnected(address)) {
I ran `npm run network 100 2> test-**.txt` for three variants 5 times:
1) one without this change
2) one with this change
3) one with this change but I remove other check from `_onNewConnection`

Firstly, we get actually race conditions _without_ this change (1) (pairs of nodes continually connecting & disconnecting without stop).

Both options (2) and (3) work much better, actually option (3) leads to lower amount of debug messages? So I'm wondering would it actually make sense to keep this and _remove_ the duplicate detection logic inside `_onNewConnection`?

2020-03-23 11:36 UTC, harbu commented on src/logic/Node.js
> +                        const node = result.value
Assuming this is intentional, I think we should just then remove method `_subscribeToStreamOnNode`  and move stuff here? The problem I see is that method `_subscribeToStreamOnNode` no longer does not do what it claims. If I need to call `_subscribeToStreamOnNode` in future from somewhere else in this class, I will need to remember to do addInboundNodes/addOutBoundNodes/emit otherwise it won't properly subscribe.

2020-03-23 12:18 UTC, mirpo commented on src/connection/WsEndpoint.js
> +            if (this.isConnected(address)) {
Agree, in separate PR

2020-03-23 12:20 UTC, mirpo commented
About _subscribeToStreamOnNode. I check in call ` if (this.streams.hasInboundNode(streamId, node) && this.streams.hasOutboundNode(streamId, node))` it means that 
```
this.streams.addInboundNode(streamId, node)
this.streams.addOutboundNode(streamId, node)
```
were called before. If you want for readability, I can add calls if first if, but they'll be useless


```
async _subscribeToStreamOnNode(node, streamId) {
        if (this.streams.hasInboundNode(streamId, node) && this.streams.hasOutboundNode(streamId, node)) {
            this.emit(events.NODE_SUBSCRIBED, {
                streamId,
                node
            })
            return node
        }

        return this.protocols.nodeToNode.sendSubscribe(node, streamId).then((nodeId) => {
            this.streams.addInboundNode(streamId, node)
            this.streams.addOutboundNode(streamId, node)

            this.emit(events.NODE_SUBSCRIBED, {
                streamId,
                node
            })
            return nodeId
        })
    }
```

2020-03-23 12:41 UTC, mirpo commented on src/connection/WsEndpoint.js
> +        //
ws/ws emits 
```
const err = new Error(message);
  Error.captureStackTrace(err, abortHandshake);
```
uws emits standard error too

2020-03-23 13:53 UTC, harbu commented on src/connection/WsEndpoint.js
> +            if (this.isConnected(address)) {
Yup

2020-03-23 14:18 UTC, harbu commented
What about

```js
async _subscribeToStreamOnNode(node, streamId) {
    if (!this.streams.hasInboundNode(streamId, node) || !this.streams.hasOutboundNode(streamId, node)) {
        await this.protocols.nodeToNode.sendSubscribe(node, streamId)
    }

    this.streams.addInboundNode(streamId, node)
    this.streams.addOutboundNode(streamId, node)

    this.emit(events.NODE_SUBSCRIBED, {
        streamId,
        node
     })

    return node
}
```

Or if you'd rather avoid `await` then maybe

```js
_subscribeToStreamOnNode(node, streamId) {
    let p
    if (this.streams.hasInboundNode(streamId, node) && this.streams.hasOutboundNode(streamId, node)) {
        p = Promise.resolve(node)
    } else {
        p = this.protocols.nodeToNode.sendSubscribe(node, streamId)
    }

    return p.then(() => {
        this.streams.addInboundNode(streamId, node)
        this.streams.addOutboundNode(streamId, node)

        this.emit(events.NODE_SUBSCRIBED, {
            streamId,
            node
        })

        return node
    })
}
```

Would these work?

2020-03-23 14:18 UTC, harbu requested changes

2020-03-23 14:18 UTC, harbu commented on src/connection/WsEndpoint.js
> +        //
Meh, sort of annoying decision from library author(s). Oh well. I see you changed to `console.error` so resolving.

2020-03-23 14:51 UTC, harbu approved these changes
LGTM

2020-03-23 14:56 UTC, merged