Instruction Throttling
streamr-dev/network-old pull request #428
Opened 2020-07-08 08:59 UTC by harbu

In this PR the logic of instruction handling on node side is changed as follows.

1. Node maintains an instance of `InstructionThrottler` during its lifecycle.
2. Upon receiving an instruction form tracker, it calls `InstructionThrottler#add` to enqueue the instruction.
3. `InstructionThrottler` invokes a callback supplied by Node (i.e. `Node#handleTrackerInstruction`) whenever a new instruction should be handled.

The class `InstructionThrottler` makes sure that no more than one instruction is handled at a time. While an instruction is being handled and a new instruction arrives, it enqueues the new instruction. If several instructions with the same streamId arrive during handling, it will keep only the latest one around (basically the one with the highest counter).

## Some considerations
- This does add complexity to the instruction handling logic. It would be nice if we could somehow check if this change brings more stability to the network.
-  A previous version of this change had a less strict invariant. It allowed for more than one instruction to be handled at a time given that they operate on different streams. (So basically max 1 instruction under handling at a time per streamId.)

2020-07-08 12:43 UTC, juslesan approved these changes
This change seems to remove the issue of tracker sending instructions with more than 5 connections. Tested with 16, 32, 64, 128, 256 and 512 node stream topologies on emulator.

2020-07-10 11:51 UTC, harbu commented
This should be okay, but probably worth fixing memory leak issue before merging this.

2020-07-10 12:09 UTC, mirpo requested changes

2020-07-10 12:09 UTC, mirpo commented on src/logic/InstructionThrottler.js
> +        this.timeout = null
not in use?

2020-07-10 12:09 UTC, mirpo commented on src/logic/InstructionThrottler.js
> +        clearTimeout(this.timeout)
not in use?

2020-07-20 08:09 UTC, merged