Geolocation
streamr-dev/network-old pull request #443
Opened 2020-08-10 14:48 UTC by juslesan

- Nodes now report defined location data on status to 

- Leaves the option for real time updates in the future

- Tracker saves location data and has an endpoint for fetching the data.

2020-08-11 06:16 UTC, mirpo requested changes
LGFM

2020-08-11 06:16 UTC, mirpo commented on bin/tracker.js
> +            throw Error('Node not found')
What it does? Returns `JSON` error? Or some `HTTP` error?

2020-08-11 06:16 UTC, mirpo commented on src/composition.js
>      const peerInfo = PeerInfo.newTracker(id, name)
`defaultLocation` is not in use?

2020-08-11 06:16 UTC, mirpo commented on src/composition.js
>      return startEndpoint(host, port, peerInfo, advertisedWsUrl).then((endpoint) => {
Maybe location is a part of `PeerInfo`? For discussion.

2020-08-11 06:16 UTC, mirpo commented on src/logic/Tracker.js
> +        const { location } = status
`const { rtts, location } = status`

2020-08-11 06:36 UTC, juslesan commented on src/composition.js
>      return startEndpoint(host, port, peerInfo, advertisedWsUrl).then((endpoint) => {
Yes, I was thinking about this possibility also. Maybe it's a better idea to add it there

2020-08-11 06:37 UTC, juslesan commented on src/composition.js
>      const peerInfo = PeerInfo.newTracker(id, name)
It's not necessary here but could be used to add locations to the trackers in the future

2020-08-11 06:39 UTC, mirpo commented on src/composition.js
>      const peerInfo = PeerInfo.newTracker(id, name)
Let's remove it, if it's not in use now.

2020-08-11 06:39 UTC, mirpo commented on src/composition.js
>      return startEndpoint(host, port, peerInfo, advertisedWsUrl).then((endpoint) => {
I think we should do it now.

2020-08-11 06:41 UTC, juslesan commented on bin/tracker.js
> +            throw Error('Node not found')
Here tracker returns {"statusCode":500,"error":"Internal Server Error","message":"Node not found"} to clients

2020-08-12 07:16 UTC, harbu approved these changes

2020-08-12 10:18 UTC, merged