One tracker port and SSL support
streamr-dev/network-old pull request #456
Opened 2020-09-28 11:50 UTC by mirpo

- added SSL support 
- added test for all tracker endpoints (as we are going to use them for public service)
- added metrics endpoint for the tracker

breaking change:
`startTracker` now expects config object. if it looks good I can refactor `startNetworkNode` and `startStorageNode`,

2020-09-28 14:43 UTC, timoxley reviewed
The radix removal seems worse to me? Some nitpicking and related/unrelated suggestions, but otherwise lgtm.

2020-09-28 14:43 UTC, timoxley commented on src/logic/Tracker.js
> +            if (streamId && !Number.isNaN(partition) && partition >= 0) {
Note `Number.isNaN(Infinity) // false`

You probably actually want: `Number.isSafeInteger(partition)`

2020-09-28 14:43 UTC, timoxley commented on src/identifiers.js
> +        return new StreamIdAndPartition(id, parseInt(partition))
This seems… worse? why

2020-09-28 14:43 UTC, timoxley commented on src/logic/Tracker.js
> +                askedStreamKey = new StreamIdAndPartition(streamId, parseInt(partition))
again why remove radix

2020-09-28 14:43 UTC, timoxley commented on test/benchmarks/overlay-topology-randomness.js
> +const nodeIdToIdx = (nodeId) => parseInt(nodeId) - 1
again why remove radix

2020-09-28 14:43 UTC, timoxley commented on .eslintrc.js
> +        radix: ['error', 'as-needed'],
why remove radix

2020-09-28 14:43 UTC, timoxley commented on bin/tracker.js
> +    .option('--exposeHttpEndpoints <exposeHttpEndpoints>', 'exposeHttpEndpoints', true)
Maybe could do with better description, seems weird that a flag defaulting to a boolean would take a parameter

2020-09-28 14:43 UTC, timoxley commented on bin/tracker.js
> +            maxNeighborsPerNode: parseInt(program.maxNeighborsPerNode),
why no radix

2020-09-28 14:43 UTC, timoxley commented on bin/tracker.js
> +        logger.info('started tracker id: %s, privateKeyFileName: %s, certFileName: %s\n, '
Consider logging an object with `%o`, gives you auto-named fields formatted on a single line:

```js
logger.info('started tracker: &o', {
  id,
  name,
  ...program
})
```

2020-09-28 14:43 UTC, timoxley commented on bin/tracker.js
>                  const metrics = await tracker.getMetrics()
ooo  unrelated to this PR, but should never do async work inside a `setInterval`
If `await tracker.getMetrics()` ever takes longer than the interval, you can end up queuing endless work potentially crashing the process.

Additionally `setInterval` is bad. If the event loop gets blocked for a significant period, e.g. performing a massive GC or doing a debug memory snapshot, so you can end up running a large number of the `setInterval` callbacks in quick succession… which could also blow the process up by trying to do too much work in one go, or in this case could give you funky metrics by sending the same metrics object N times because all the queued `setInterval` callbacks executed at once. Additionally if there's queued calls and they happen to resolve out-of-order, then you're going to be sending your metrics results out-of-order, which could be misleading.

To ensure only one of these is ever happening at once, and callbacks execute at most once every `program.metricsInterval`, this should be a recursive function with a `setTimeout`, something like:

```js
;(async function pollMetrics() {
    const metrics = await tracker.getMetrics()
    // send metrics to streamr.network
    if (client) {
        client.publishHttp(program.streamId, metrics)
    }

    // output to console
    if (program.metrics) {
        logger.info(JSON.stringify(metrics, null, 3))
    }
    clearTimeout(pollMetrics.t) // always clear timeout before you set it
    pollMetrics.t = setTimeout(pollMetrics, program.metricsInterval)
}())
```

2020-09-28 14:43 UTC, timoxley commented on bin/tracker.js
> +                    logger.info(JSON.stringify(metrics, null, 3))
3 spaces :/

2020-09-28 14:43 UTC, timoxley commented on bin/tracker.js
>          process.exit(1)
Also unrelated, but this should also probably be `pino.final(logger).error(err)` otherwise the process can exit before the buffer is flushed.

https://github.com/pinojs/pino/blob/db651a51762e8b043f406a73bb19470bcf6dcff1/docs/asynchronous.md#log-loss-prevention

2020-09-28 14:43 UTC, timoxley commented on bin/tracker.js
> +            port: parseInt(program.port),
why no radix

2020-09-28 14:43 UTC, timoxley commented on bin/run.js
> +productionEnv.LOG_LEVEL = 'debug'
I wonder if this should assign a default rather than forcibly overriding whatever was set in `env`?
```js
productionEnv.LOG_LEVEL = productionEnv.LOG_LEVEL || 'debug'
```

2020-09-28 14:43 UTC, timoxley commented on src/composition.js
> +            res.writeStatus('500 streamId must be a not empty string').end()
This should probably `return` otherwise it will still run the code below

2020-09-28 14:43 UTC, timoxley commented on src/composition.js
> +            res.writeStatus('500 streamId must be a not empty string').end()
`return`

2020-09-28 14:43 UTC, timoxley commented on src/composition.js
> +            res.writeStatus('500 partition must be a positive integer').end()
`return`

2020-09-28 14:43 UTC, timoxley commented on src/composition.js
> +        if (Number.isNaN(askedPartition) || askedPartition < 0) {
`Number.isSafeInteger`

2020-09-28 14:43 UTC, timoxley commented on src/composition.js
> +        extraLogger.debug(`request to /topology/${streamId}/${askedPartition}/`)
I feel like all these logger messages should go into some kind of generic middleware, or/and should happen before any other calls so it always logs messages before potentially throwing.

This uWebsockets thing is weird. "Commercially supported" seems to actually mean "lack of examples or documentation", but maybe something like:


```js
wws.any((res, req) => {
    // http logger
    extraLogger.debug('request to %s: %s', req.getMethod(), req.getUrl())

    // attach json helper
    res.json = (...args) => {
        res.end(JSON.stringify(...args))
    }

    req.setYield(true) // make this middleware
}
```

2020-09-28 14:43 UTC, timoxley commented on src/composition.js
> +            res.writeStatus('500 streamId must be a not empty string').end()
`500` perhaps should be `422`, leave 5xx for unexpected errors and crashes?

2020-09-28 14:46 UTC, juslesan approved these changes

2020-09-29 06:25 UTC, mirpo commented on src/logic/Tracker.js
> +            if (streamId && !Number.isNaN(partition) && partition >= 0) {
Replaced to isSafeInteger, but why would I care about `Infinity`?

2020-09-29 06:29 UTC, mirpo commented on src/identifiers.js
> +        return new StreamIdAndPartition(id, parseInt(partition))
reverted radix everywhere

2020-09-29 06:32 UTC, mirpo commented on bin/tracker.js
> +    .option('--exposeHttpEndpoints <exposeHttpEndpoints>', 'exposeHttpEndpoints', true)
Good point, changed to `flag`

2020-09-29 06:40 UTC, mirpo commented on bin/tracker.js
> +        logger.info('started tracker id: %s, privateKeyFileName: %s, certFileName: %s\n, '
Can't do this, it outputs the whole `commander` object with all internals. Changed a bit.

2020-09-29 06:42 UTC, mirpo commented on bin/tracker.js
>                  const metrics = await tracker.getMetrics()
Okkkkk, good to know :)

2020-09-29 06:43 UTC, mirpo commented on bin/tracker.js
> +                    logger.info(JSON.stringify(metrics, null, 3))
Yeah, more readable

2020-09-29 06:45 UTC, mirpo commented on bin/tracker.js
>          process.exit(1)
I took from official documentation.
https://getpino.io/#/docs/help?id=exit-logging#/docs/help?id=exit-logging#/docs/help?id=exit-logging

2020-09-29 06:48 UTC, mirpo commented on bin/tracker.js
>          process.exit(1)
Added

2020-09-29 06:48 UTC, mirpo commented on bin/run.js
> +productionEnv.LOG_LEVEL = 'debug'
Good point

2020-09-29 06:50 UTC, mirpo commented on src/composition.js
> +            res.writeStatus('500 streamId must be a not empty string').end()
Yeah, just copy-pasta from `fast` implementation

2020-09-29 06:52 UTC, mirpo commented on src/composition.js
> +        extraLogger.debug(`request to /topology/${streamId}/${askedPartition}/`)
Need to test separately

2020-09-29 07:19 UTC, harbu requested changes

2020-09-29 07:19 UTC, harbu commented on package.json
> +    "got": "^11.7.0",
I would prefer we use `node-fetch`. Not because find it to be best library, but to be consistent with other projects (such as broker).

2020-09-29 07:19 UTC, harbu commented on bin/tracker.js
> +                    logger.info(JSON.stringify(metrics, null, 3))
He is probably referring to odd number. Not 2 or 4 😄

2020-09-29 07:19 UTC, harbu commented on src/composition.js
> +const writeCorsHeaders = (res, req) => {
All this HTTP stuff needs to be moved to a separate file. This file is about composing functionality for end-user needs and handling configuring.

2020-09-29 07:19 UTC, harbu commented on src/composition.js
> +        if (streamId === '') {
Not sure we would every hit this with the mapping `wss.get('/topology/', ...)` above though?

2020-09-29 07:19 UTC, harbu commented on src/composition.js
> +            extraLogger.error(`422 partition must be a positive integer, askedPartition: ${askedPartition}`)
From the server-side's viewpoint it is not an error for a user to send an invalid partition. The server is doing exactly what is supposed to: rejecting the request. It is a user request error. So IMO we shouldn't log an error.

2020-09-29 07:19 UTC, harbu commented on src/composition.js
> +    const [wss, listenSocket] = await startWebSocketServer(host, port, privateKeyFileName, certFileName)
To be consistent with rest of functions I guess you could keep
```js
const ep = startEndpoint(host, port, peerInfo, advertisedWsUrl, pingInterval)
```
as in other functions

and then attach to HTTP endpoints
```js
trackerHttpEndpoints(endpoint.wss, tracker)
```

2020-09-29 07:19 UTC, harbu commented on test/integration/tracker-endpoints.test.js
> +        await wait(1000)
Replace sleep with event awaiting or waitForCondition for quicker tests.

2020-09-29 08:23 UTC, mirpo commented on bin/tracker.js
> +                    logger.info(JSON.stringify(metrics, null, 3))
🍖

2020-09-29 08:35 UTC, mirpo commented on src/composition.js
> +        if (streamId === '') {
nope

2020-09-29 09:06 UTC, harbu commented on src/composition.js
> +        if (streamId === '') {
So I guess my question would then be, why have code that is never run?

2020-09-29 09:07 UTC, harbu commented on src/composition.js
> +            extraLogger.error(`422 partition must be a positive integer, askedPartition: ${askedPartition}`)
You didn't address this.

2020-09-29 09:37 UTC, harbu approved these changes

2020-09-29 13:16 UTC, timoxley approved these changes

2020-09-29 13:16 UTC, timoxley commented on test/integration/tracker-endpoints.test.js
> +            const jsonResult = await got(`http://${LOCALHOST}:${trackerPort}/topology/stream-1/0/`).json()
actually… why try/catch around all these? And why use `done()` at all?

2020-09-30 06:54 UTC, merged