Latency calculations
streamr-dev/network-old pull request #477
Opened 2020-12-01 10:10 UTC by bearni95

2020-12-01 10:44 UTC, harbu requested changes

2020-12-01 10:44 UTC, harbu commented on test/integration/latency.test.js
> +        tracker._formAndSendInstructions = () => {}
Is this disabling necessary? Can be probably removed.

2020-12-01 10:44 UTC, harbu commented on test/integration/latency.test.js
> +        node2 = await startNetworkNode({
`node2` not used in this test. Can be removed?

2020-12-01 10:44 UTC, harbu commented on test/integration/latency.test.js
> +describe('TestLatency', () => {
It is convention to use camel case when we are referring to a specific class. Here we don't have a class, so maybe a free form description is more appropriate, e.g. `latency metrics`.

2020-12-01 10:44 UTC, harbu commented on test/integration/latency.test.js
> +        tracker = await startTracker({
You may not need `tracker` in this test actually with only one node.

2020-12-01 10:44 UTC, harbu commented on test/integration/latency.test.js
> +    it('Should send a single message to Node1 and collect latency', (done) => {
start description with lowercase to be consistent with other tests

2020-12-01 10:44 UTC, harbu commented on test/integration/latency.test.js
> +    it('Should send a bunch of messages to Node1 and collect latency', async (done) => {
start description with lowercase to be consistent with other tests

2020-12-01 10:44 UTC, harbu commented on test/integration/latency.test.js
> +    it('TestLatency should fetch empty metrics', async () => {
start description with lowercase to be consistent with other tests

2020-12-02 12:04 UTC, bearni95 commented on test/integration/latency.test.js
> +        tracker = await startTracker({
The node initialization throws an error when started without a tracker, seems to need it

2020-12-02 14:37 UTC, harbu approved these changes

2020-12-02 14:42 UTC, merged