NET-116: Add tracker endpoint /topology-union/
streamr-dev/network-old pull request #482
Opened 2020-12-11 16:51 UTC by teogeb

Returns all known connections between nodes, across all streams. Cache the result for 15 seconds.

2020-12-14 13:31 UTC, harbu requested changes

2020-12-14 13:31 UTC, harbu commented on src/logic/Tracker.js
> +        const nodeMaps = Object.values(this.overlayPerStream).map(topology => new Map(Object.entries(topology.nodes)))
As `topology.nodes` could be thought of as a private member of `OverlayTopology`, I feel a bit uneasy of accessing it directly from other classes (at least without TypeScript, in which we can explicitly declare a field public). Could `OverlayTopology#state()` be used here? Or alternatively, creating a getter method on OverlayTopology such as `OverlayTopology#getNodes`.

2020-12-14 13:31 UTC, harbu commented on src/helpers/trackerHttpEndpoints.js
> +    wss.cachedJsonGet = (endpoint, maxAge, jsonFactory) => { // eslint-disable-line no-param-reassign
Hmm.. don't see param re-assignment though? ``// // eslint-disable-line no-param-reassign``

2020-12-14 13:31 UTC, harbu commented on src/helpers/trackerHttpEndpoints.js
> +        return Object.fromEntries(new Map(Array.from(topologyUnion, ([key, value]) => [key, Array.from(value)])))
Wondering if these conversions really necessary?

2020-12-14 13:39 UTC, kare commented
> NET-115 Add dependency to org.jetbrains:annotations

@teogeb This is not NET-115 ticket!

2020-12-14 15:26 UTC, teogeb commented on src/helpers/trackerHttpEndpoints.js
> +    wss.cachedJsonGet = (endpoint, maxAge, jsonFactory) => { // eslint-disable-line no-param-reassign
ESlint is complaining about the `wss` parameter of trackerHttpEndpoints function, which we modify:
`Assignment to property of function parameter 'wss'  no-param-reassign`

There is no optimal place for initializing this kind of middleware method. Maybe it is ok inside `trackerHttpEndpoints` as that utility method is specifically for HTTP requests.

2020-12-14 17:06 UTC, teogeb commented on src/logic/Tracker.js
> +        const nodeMaps = Object.values(this.overlayPerStream).map(topology => new Map(Object.entries(topology.nodes)))
Created getter `OverlayTopology#getNodes`.

2020-12-14 17:23 UTC, teogeb commented on src/helpers/trackerHttpEndpoints.js
> +        return Object.fromEntries(new Map(Array.from(topologyUnion, ([key, value]) => [key, Array.from(value)])))
Simplified the logic: now the intermediate state is just a plain object, not Map. The data structure is always so small that it doesn't make any performance difference. 

Added dependency to `lodash` library. Currently only the `mapValues` function is used, but I guess we'll use other functions in the near future, too. When we use "standard" lodash functions (instead of our own implementations), the code is more readable as many developers already know those basic functions and their behaviour.

2020-12-15 16:43 UTC, harbu approved these changes

2020-12-15 16:44 UTC, merged