WIP: NET-124: Typescript tests
streamr-dev/network-old pull request #496
Opened 2021-01-07 16:31 UTC by teogeb

2021-01-14 13:40 UTC, harbu requested changes
Let's remove unneeded packages + are all new the eslint disabled things necessary?

Rest of my comments about enhancing typing can be ignored and done later imo.

2021-01-14 13:40 UTC, harbu commented on .eslintrc.js
> +        // TODO remove some of these is possible
What about this TODO and these ignores, seems like things to address since they come from `@typescript-eslint/recommended`?

2021-01-14 13:40 UTC, harbu commented on package.json
>      "eslint-config-streamr-nodejs": "^1.3.0",
Probably eslint packages here we can get rid of now then? Like 
```js
eslint-config-airbnb-base
eslint-config-streamr-nodejs
eslint-plugin-import
eslint-plugin-import-order
eslint-plugin-promise
```

2021-01-14 13:40 UTC, harbu commented on test/integration/Connection.test.ts
> +function onConnectPromise(functions: any) {
`functions` could be typed here for type safety

2021-01-14 13:40 UTC, harbu commented on test/integration/counter-filtering-in-tracker.test.ts
> +} as any)
Should not have to use `any` here though as return type is `Status`?

2021-01-14 13:40 UTC, harbu commented on test/integration/l3-resend-requests.test.ts
> +const typesOfStreamItems = async (stream: any) => {
stream could be typed to be `Readable` or `NodeJS.ReadableStream` or whatever the type is

2021-01-14 13:40 UTC, harbu commented on test/integration/request-resend-from-uninvolved-node.test.ts
> +const typesOfStreamItems = async (stream: any) => {
same comment as before

2021-01-14 13:40 UTC, harbu commented on test/unit/InstructionCounter.test.ts
> +        const filtered = instructionCounter.filterStatus(status as any, 'node')
could variable `status` be typed in this test?

2021-01-14 13:44 UTC, teogeb commented on .eslintrc.js
> +        // TODO remove some of these is possible
Yes, will be handled in NET-125 (see the PR description).

2021-01-14 13:46 UTC, teogeb commented on package.json
>      "eslint-config-streamr-nodejs": "^1.3.0",
Yes, good point. In NET-125.

2021-01-14 14:05 UTC, teogeb commented on test/integration/Connection.test.ts
> +function onConnectPromise(functions: any) {
Fixed

2021-01-14 14:05 UTC, teogeb commented on test/integration/counter-filtering-in-tracker.test.ts
> +} as any)
Status interface has these field that that are not in the mock object:
- rtts: Rtts
- location: Location
- started: string

Changed the return type to Partial<Status> and added casts to places where we use the object.

2021-01-14 14:12 UTC, teogeb commented on test/integration/l3-resend-requests.test.ts
> +const typesOfStreamItems = async (stream: any) => {
Modified to `NodeJS.ReadableStream` and added cast when calling `waitForStreamToEnd` (which requires `Readable`)

2021-01-14 14:15 UTC, teogeb commented on test/unit/InstructionCounter.test.ts
> +        const filtered = instructionCounter.filterStatus(status as any, 'node')
Same as in earlier comment: using Partial<Status> as some fields are missing.

2021-01-15 08:23 UTC, harbu approved these changes

2021-01-15 11:13 UTC, merged