Per stream instruction throttler
streamr-dev/network-old pull request #510
Opened 2021-02-01 15:23 UTC by juslesan

- Change bin/network.js and bin/subscriber.js streams flag to subscribe all nodes to n amount of streams
- Rework InstructionThrottler to work on per stream basis. Solves throughput issues with multi stream throttling

2021-02-05 15:25 UTC, harbu requested changes

2021-02-05 15:25 UTC, harbu commented on src/logic/InstructionThrottler.ts
> +        if (!this.instructionCounter[streamId] || this.instructionCounter[streamId]) {
This condition looks wrong?

2021-02-05 15:25 UTC, harbu commented on src/logic/InstructionThrottler.ts
> +                return
The `return` here will not short circuit the forEach-loop, so it will go through the entire list anyways even if a `true` is found earlier since the `return` applies to each instance of the inner function. To short circuit the search use traditional for loop or `find` or `some` e.g.
 ```js
return Object.values(this.ongoingPromises).some((p) => p.handling))
```

2021-02-05 15:25 UTC, harbu commented on test/unit/InstructionThrottler.test.ts
> +        console.log()
rm

2021-02-05 15:25 UTC, harbu commented on test/integration/tracker-node-reconnect-instructions.test.ts
> +        await waitForEvent(nodeOne, NodeEvent.NODE_UNSUBSCRIBED)
To check that a disconnection actually occurred as the title of the test case implies, I think it would be worth checking that
```js
expect(Object.keys(nodeTwo.nodeToNode.endpoint.connections).length).toBe(2)
```
holds before sending the instruction.

2021-02-05 17:02 UTC, juslesan commented on src/logic/InstructionThrottler.ts
> +        if (!this.instructionCounter[streamId] || this.instructionCounter[streamId]) {
Yeah not sure how that got there

2021-02-08 08:06 UTC, harbu approved these changes

2021-02-10 15:08 UTC, merged