Net-25: node-to-node connections communicate and use the latest version supported by both
streamr-dev/network-old pull request #556
Opened 2021-05-07 12:40 UTC by juslesan

- Node-to-Node (WebRTC) connections exchange information of their control and message layer protocol versions

2021-05-07 19:58 UTC, timoxley requested changes
The `=== []` checks need to be fixed but otherwise lgtm.

2021-05-07 19:58 UTC, timoxley commented on src/connection/NegotiatedProtocolVersions.ts
> +type negotiatedProtocolVersion = { controlLayerVersion: number, messageLayerVersion: number }
aren't Types conventionally CamelCase (uppercase first letter), unless they're primitives like `string`? Doesn't really matter just thought this looked odd

2021-05-07 19:58 UTC, timoxley commented on src/connection/NegotiatedProtocolVersions.ts
> +        this.negotiatedProtocolVersions = {}
`Object.create(null)`

2021-05-07 19:58 UTC, timoxley commented on src/connection/NegotiatedProtocolVersions.ts
> +    getNegotiatedProtocolVersion(peerId: string): negotiatedProtocolVersion | null | never {
curious why `| never`

2021-05-07 19:58 UTC, timoxley commented on src/connection/NegotiatedProtocolVersions.ts
> +            throw new Error('Missing version negotiation! Must give controlLayerVersions and messageLayerVersions as query parameters!')
`arr === []` will never be true because `[]` generates a new object, and `===` checks object equality.

You probably want to check array length:

`(!controlLayerVersions || controlLayerVersions.length === 0) && (! messageLayerVersions || messageLayerVersions.length === 0)`

2021-05-07 19:58 UTC, timoxley commented on src/connection/PeerInfo.ts
> +        if (!controlLayerVersions || controlLayerVersions === []) {
Same here, can't do `=== []`

2021-05-07 19:58 UTC, timoxley commented on src/connection/WebRtcEndpoint.ts
> +            this.negotiatedProtocolVersions.removeNegotiatedProtocolVersion(targetPeerId)
hm… is it possible that this will wipe out NegotiatedProtocolVersion information for another connection to the same peer? Maybe it should be inside the `if (this.connections[targetPeerId] === connection) {` above?

2021-05-07 19:58 UTC, timoxley commented on src/connection/WsEndpoint.ts
> +    getNegotiatedMessageLayerProtocolVersionOnNode(peerId: string): number | null {
`: number | null`

I don't think `Math.max` can return `null`, but it can return `-Infinity` (`Math.max()`) or `NaN` (`Math.max('a')`). Also note `Math.max(null)` is `0`.

2021-05-07 19:58 UTC, timoxley commented on src/connection/WsEndpoint.ts
> +        return Math.max(...this.peerInfo.controlLayerVersions)
hm, so why doesn't this need to use `peerId`?

2021-05-07 19:58 UTC, timoxley commented on src/protocol/NodeToNode.ts
> +        const messageLayerVersion = this.getNegotiatedMessageLayerProtocolVersionOnNode(receiverNodeId)
Wonder if maybe these could be a single function that returns a tuple with both versions, since most/all of the time you'll want both?

```js
const [controlLayerVersion, messageLayerVersion] = getNegotiatedProtocolVersionsOnNode(receiverNodeId)
```

2021-05-07 19:58 UTC, timoxley commented on src/protocol/NodeToNode.ts
> +            || Math.max(...this.endpoint.getPeerInfo().messageLayerVersions)
curious about the scenario that needs the `||`

2021-05-07 19:58 UTC, timoxley commented on src/protocol/NodeToNode.ts
> +            || Math.max(...this.endpoint.getPeerInfo().messageLayerVersions)
Note if it's possible for `...this.endpoint.getPeerInfo().messageLayerVersions` to be `[]` then `Math.max()` will give `-Infinity`. Might not be possible, but since versions should always be >= 0, you can easily throw a `0` in there to prevent this from ever returning `-Infinity` i.e. `Math.max(0, ...this.endpoint.getPeerInfo().messageLayerVersions)`

2021-05-07 19:58 UTC, timoxley commented on src/connection/WsEndpoint.ts
> +                        const messageLayerVersionsArray = messageLayerVersions.split(',').map((version) => parseInt(version))
Possible you want to filter out funky values like `NaN` and `-Infinity` here?

Also might want to add `10` as the radix i.e. `parseInt(version, 10)`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#octal_interpretations_with_no_radix

2021-05-07 19:58 UTC, timoxley commented on src/connection/PeerBook.ts
> +        return peerId.peerId
Maybe the `peerId` variable here should be called `peerInfo` so then this reads like `peerInfo.peerId`

2021-05-07 19:58 UTC, timoxley commented on src/connection/PeerBook.ts
>  export class PeerBook {
I like what you've done here, much tidier.

2021-05-07 19:58 UTC, timoxley commented on src/protocol/NodeToNode.ts
> +        const messageLayerVersion = this.getNegotiatedMessageLayerProtocolVersionOnNode(receiverNodeId)
Or even better, returns a `NegotiatedProtocolVersions`, but add the below magic to it so the above iterable destructuring still works:
```js
class NegotiatedProtocolVersions {
    // …
    [Symbol.iterator]() {
        return [this.controlLayerVersion, this.messageLayerVersion][Symbol.iterator]()
    }
}
```
or could make `controlLayerVersion` and `messageLayerVersion` into `public readonly` then use object destructuring:
```js
const { controlLayerVersion, messageLayerVersion } = getNegotiatedProtocolVersionsOnNode(receiverNodeId)
```

2021-05-07 19:58 UTC, timoxley commented on src/protocol/NodeToNode.ts
> +        const messageLayerVersion = this.getNegotiatedMessageLayerProtocolVersionOnNode(receiverNodeId)
or do nothing, just some ideas, your call, `getNegotiatedControlLayerProtocolVersionOnNode` and `getNegotiatedMessageLayerProtocolVersionOnNode` are quite a mouthful though

2021-05-07 20:01 UTC, timoxley commented on src/connection/NegotiatedProtocolVersions.ts
> +        this.negotiatedProtocolVersions = {}
https://linear.app/streamr/issue/NET-270/using-as-a-dictionary-creates-potential-for-security-issues-or-bugs

2021-05-07 20:08 UTC, timoxley commented on src/connection/NegotiatedProtocolVersions.ts
> +        }
Could this maybe be a `NegotiatedProtocolVersions` object

2021-05-07 20:08 UTC, timoxley commented on src/connection/NegotiatedProtocolVersions.ts
> +export class NegotiatedProtocolVersions {
Wondering if maybe the `max` calculations etc could live in here.

2021-05-07 20:14 UTC, timoxley commented on test/integration/node-to-node-protocol-version-negotiation.test.ts
> +            errors += 1
Doesn't need to change but just a headsup that I've seen a few cases where the error path had some bug that caused something like a "undefined is not a function" or something other than the expected error, and this went undetected because I didn't check the error type in the error handler.
```js
await expect(async () => (
    ep3.connect('node-endpoint1', 'tracker')
)).rejects.toThrow('no shared version') // matches against message, can be partial string match or even a regex
```
Ca

2021-05-07 20:14 UTC, timoxley commented on test/integration/node-to-node-protocol-version-negotiation.test.ts
> +        ep2.on(wrtcEvent.MESSAGE_RECEIVED, (peerInfo, data) => {
suggest using `ep2.once` so this can't possibly run more than once

2021-05-07 20:20 UTC, juslesan commented on src/connection/NegotiatedProtocolVersions.ts
> +            throw new Error('Missing version negotiation! Must give controlLayerVersions and messageLayerVersions as query parameters!')
Good catch, I just copied this from the old NET-25 PR and didn't give it much though

2021-05-07 20:59 UTC, juslesan commented on test/integration/node-to-node-protocol-version-negotiation.test.ts
> +            errors += 1
The problem here is that the error can change. Sometimes it's a connection timeout error when the next signalling message is never received and sometimes its a 'no shared version' error. Basically, it seems to mostly depend on timing.

It should be possible to check for different types of errors of course but in this case the most important point is that the connection is closed

2021-05-08 01:37 UTC, timoxley commented on test/integration/node-to-node-protocol-version-negotiation.test.ts
> +            errors += 1
understood

2021-05-08 01:37 UTC, timoxley approved these changes
lgtm

2021-05-10 10:44 UTC, harbu requested changes
Looks good to me. A few thoughts that I think we should address.

### Version handling in `WsEndpoint`
Strictly speaking, we don't need version handling in `WsEndpoint` since this ticket was concentrated on versions between two nodes, not node and tracker. That being said, it is easy to see that in the future we may want to also negotiate versions between node and tracker. Furthermore, if we want to keep around the possibility of using `WsEndpoint` between nodes, having version negotiation on `WsEndpoint` is a must.

Could we use the `NegotiatedProtocolVersion` class in `WsEndpoint` similarly to how is done in `WebRtcEndpoint`? Then we could delegate all calculations to that class and have it be the single source of truth.


### Default version in the presence of no version information
To my understanding, the code works so that if no protocol  version information is supplied we assume the latest versions of protocols are used. Wondering if it should just be an error not to supply version information? Argument being that you catch the erroneous situation earlier vs. receiving latest version messages.

### Unit test for NegotiatedProtocolVersions
Although it gets tested indirectly by `node-to-node-protocol-version-negotiation.test.ts`, the class could use a unit test of its own covering edge cases etc. Generally just makes it quicker to spot any errors when making e.g. changes to the class.

2021-05-10 10:44 UTC, harbu commented on .idea/jsLibraryMappings.xml
> -<?xml version="1.0" encoding="UTF-8"?>
Intentional removal?

2021-05-10 10:44 UTC, harbu commented on src/connection/NegotiatedProtocolVersions.ts
> +    validateProtocolVersions(controlLayerVersions: number[], messageLayerVersions: number[]): number[] {
Looking at the usages of method `validateProtocolVersions` it always precedes an invocation to method `addNegotiatedProtocolVersion`. Thus I would turn this private, and make `addNegotiatedProtocolVersion` call this method before adding a protocol version to the object. This has the added benefit on ensuring that the following invariant is always true: any version present in field `this.negotiatedProtocolVersions` has undergone validation.

2021-05-10 10:44 UTC, harbu commented on src/connection/PeerBook.ts
>      getPeerInfo(peerAddress: string): PeerInfo | null | never {
Hmm `never` can be removed from type signature. Maybe this used to throw an error or something?

2021-05-10 10:44 UTC, harbu commented on src/connection/WebRtcEndpoint.ts
> +            try {
Duplicated code fragment with above, move to helper method in case future changes needed?

2021-05-10 10:44 UTC, harbu commented on src/connection/WebRtcEndpoint.ts
> +        return this.negotiatedProtocolVersions.getNegotiatedProtocolVersion(peerId)?.messageLayerVersion || null
Don't think the `|| null` is strictly needed here and below. Since the "elvis" operator  here `this.negotiatedProtocolVersions.getNegotiatedProtocolVersion(peerId)?.` will return a null if `this.negotiatedProtocolVersions.getNegotiatedProtocolVersion(peerId)` is a null. And if we get a `messageLayerVersion` it will always be a number based on its type.

2021-05-10 10:44 UTC, harbu commented on src/connection/PeerInfo.ts
> +        return new PeerInfo(peerId, PeerType.Tracker, defaultControlLayerVersions, defaultMessageLayerVersions, peerName, location)
For completeness, these static helpers could take in `controlLayerVersions` and `messageLayerVersions`  parameters.

2021-05-10 10:44 UTC, harbu commented on src/connection/WsEndpoint.ts
> +    getNegotiatedMessageLayerProtocolVersionOnNode(peerId: string): number | null {
You can avoid having to use `// eslint-disable-next-line @typescript-eslint/no-unused-vars` by prefixing the unused parameter with underscore, i.e. `_peerId: string` in this case.

2021-05-10 10:44 UTC, harbu commented on src/connection/WsEndpoint.ts
> +        return Math.max(...this.peerInfo.messageLayerVersions)
Wouldn't we want to take the maximum of the intersection of the two sets here?
```ts
const myVersions = this.peerInfo.messageLayerVersions
const theirVersions = this.peerBook.getByPeerId(peerId).messageLayerVersions
const sharedVersion = // intersection(myVersions, theirVersions)
return max(sharedVersions)
```

2021-05-10 10:44 UTC, harbu commented on src/connection/WsEndpoint.ts
> +        return Math.max(...this.peerInfo.controlLayerVersions)
Same question as above

2021-05-10 10:44 UTC, harbu commented on src/connection/WsEndpoint.ts
> +        return Math.max(...this.peerInfo.messageLayerVersions)
Hmm.. would it be easiest to just use `NegotiatedProtocolVersions` in this class (similar to `WebRtcEndpoint`)?

2021-05-10 10:44 UTC, harbu commented on src/protocol/NodeToNode.ts
> +    getNegotiatedProtocolVersionsOnNode(peerId: string): number[] {
Since this method always returns a tuple, you can make the type signature tighter with: `[number, number]`.

2021-05-10 10:44 UTC, harbu commented on src/protocol/NodeToNode.ts
> +            || Math.max(0, ...this.endpoint.getPeerInfo().messageLayerVersions)
Instead of `|| Math.max(0, ...this.endpoint.getPeerInfo().messageLayerVersions)` what about having a method on `NegotiatedProtocolVersions` for fetching the default version. That way you can also make sure it gets calculated once.

2021-05-10 10:44 UTC, harbu commented on test/integration/node-to-node-protocol-version-negotiation.test.ts
> +        // Need to set up TrackerNodes and WsEndpoint(s) to exchange RelayMessage(s) via tracker
:+1:

2021-05-10 10:44 UTC, harbu commented on src/protocol/NodeToNode.ts
> +            || Math.max(0, ...this.endpoint.getPeerInfo().messageLayerVersions)
Hmm.. that got me thinking, should the entire logic of
```ts
return max(intersection(myVersions, theirVersions)) || max(myVersions)
```
be encapsulated in class `NegotiatedProtocolVersions`. This would require `WsEndpoint` to use the class however. But all the version calculation would be done there then?

2021-05-10 10:44 UTC, harbu commented on test/integration/node-to-node-protocol-version-negotiation.test.ts
> +    it('negotiated protocol is removed once node is disconnected', async () => {
negotiated <del>protocol</del> version

2021-05-10 11:17 UTC, juslesan commented on src/connection/WsEndpoint.ts
> +        return Math.max(...this.peerInfo.messageLayerVersions)
I only added this function to the WS endpoint to ensure that the function exists in both endpoint types. The WS negotiated protocol is not actually used anywhere. We do still use WS for node-to-node connections in one test: `integration/delivery-of-messages-protocol-layer.test.ts` which is why I had to include the function. Maybe the WS endpoints should also fully negotiate the used protocol to ensure that WS node-to-node connections will work if we end up bringing them back.

2021-05-10 11:32 UTC, juslesan commented on src/connection/WsEndpoint.ts
> +        return Math.max(...this.peerInfo.controlLayerVersions)
> I only added these functions to the WS endpoint to ensure that the function exists in both endpoint types. The WS negotiated protocol is not actually used anywhere. We do still use WS for node-to-node connections in one test: integration/delivery-of-messages-protocol-layer.test.ts which is why I had to include the function. Maybe the WS endpoints should also fully negotiate the used protocol to ensure that WS node-to-node connections will work if we end up bringing them back.

2021-05-10 14:30 UTC, juslesan commented on src/connection/WebRtcEndpoint.ts
> +            this.negotiatedProtocolVersions.removeNegotiatedProtocolVersion(targetPeerId)
Currently there should only ever be a single connection per peer

2021-05-10 16:05 UTC, juslesan commented
> Strictly speaking, we don't need version handling in `WsEndpoint` since this ticket was concentrated on versions between two nodes, not node and tracker.

This is true. I included exchanging information of protocol versions on WSEndpoint as it will turn out to be useful in the future. For example, the tracker algorithm could take in to account that some nodes cannot connect to eaach other if they do not share protocol versions.  Alternatively, the tracker could reject WS connections from nodes that are too far behind in the versioning. That being said, I'm fine with the logic being removed for now if necessary.

2021-05-10 16:18 UTC, timoxley commented on src/protocol/NodeToNode.ts
> +            || Math.max(0, ...this.endpoint.getPeerInfo().messageLayerVersions)
Was thinking the same thing: https://github.com/streamr-dev/network/pull/556#discussion_r628480431

2021-05-11 16:01 UTC, harbu approved these changes
LGTM

2021-05-12 09:57 UTC, merged