Move composition of the layer stack away from the logic layer (#34)
streamr-dev/network-old pull request #57
Opened 2018-09-15 05:25 UTC by ptesavol

This is only the first step. Now composition of the layers is done in many places: in the executable and the tests. What do you think about encapsulating the layer composition info factories such as TrackerFactory and NodeFactory that would be the only places where the composition is done?

2018-09-15 10:00 UTC, mirpo commented
please update code, so it'll pass Travis -> eslint + existing tests

2018-09-15 10:58 UTC, harbu requested changes
LGTM; but yeah travis should pass before merge

2018-09-15 11:24 UTC, mirpo requested changes

2018-09-15 11:24 UTC, mirpo commented on publisher.js
> +    const publisher = new Publisher(new NodeToNode(connection), nodeAddress)
Maybe it's  better to something like `async createConnection`? https://github.com/streamr-dev/network/blob/master/src/connection/Connection.js#L143
Or move it to some helper file, so we can reuse it in code, tests and etc.

2018-09-15 11:24 UTC, mirpo commented on src/NetworkNode.js
> +    const node = new Node(new TrackerNode(connection), new NodeToNode(connection))
or something like Node({trackerNode: new TrackerNode(connection), nodeToNode: new NodeToNode(connection)})
so in constructor only this.protocols =

2018-09-15 11:24 UTC, mirpo commented on src/logic/Node.js
>          this.protocols.trackerNode.on(TrackerNode.events.CONNECTED_TO_TRACKER, (tracker) => this.onConnectedToTracker(tracker))
we must somehow validate that we have correct protocols, which will catch events.

2018-09-15 13:43 UTC, ptesavol commented on publisher.js
> +    const publisher = new Publisher(new NodeToNode(connection), nodeAddress)
How about adding folder called "composition" and putting there classes TrackerFactory and NodeFactory for creating the layer composition of each. It would then be easy to change the composition to something else, for example replace the libp2p connection layer with plain websockets connection layer.

2018-09-15 13:47 UTC, ptesavol commented on src/logic/Node.js
>          this.protocols.trackerNode.on(TrackerNode.events.CONNECTED_TO_TRACKER, (tracker) => this.onConnectedToTracker(tracker))
I searched the file and there was no such method as onNodeReady(), that is why I removed the code that calls that function.

2018-09-15 14:36 UTC, ptesavol commented on publisher.js
> +    const publisher = new Publisher(new NodeToNode(connection), nodeAddress)
I'll make a separate issue about this and do this next

2018-09-15 18:54 UTC, harbu approved these changes

2018-09-15 18:55 UTC, harbu commented on src/logic/Node.js
>          this.protocols.trackerNode.on(TrackerNode.events.CONNECTED_TO_TRACKER, (tracker) => this.onConnectedToTracker(tracker))
Yeah I got rid of the event in a previous commit.

2018-09-16 06:52 UTC, mirpo approved these changes

2018-09-17 07:54 UTC, merged