Specify ver
streamr-dev/network-old pull request #75
Opened 2018-09-18 16:38 UTC by mirpo

2018-09-18 16:57 UTC, harbu commented on src/check-versions.js
> +check(
Should we put this in folder `$PROJECT_ROOT/bin`? It is a pattern I have seen in node projects to put utilities/tools in a folder called bin.

2018-09-19 08:59 UTC, kare commented on package.json
> +    "check-node-version": "^3.2.0",
Please specify exact versions only from now on!

You can do either:
    % npm config set save-exact true
or
    % npm install --save --save-exact [package]

2018-09-19 09:17 UTC, kare commented on README.md
> +
I'm thinking there is a chicken or egg problem here.

npm i -g check-node-version didn't help.

```
~/src/github.com/streamr-dev/network specify_ver  % npm --version
6.4.1
~/src/github.com/streamr-dev/network specify_ver  % node --version
v8.12.0
~/src/github.com/streamr-dev/network specify_ver  % npm i

> @streamr/streamr-p2p-network@1.0.3 preinstall /Users/kkn/src/github.com/streamr-dev/network
> npm run requirements-check


> @streamr/streamr-p2p-network@1.0.3 requirements-check /Users/kkn/src/github.com/streamr-dev/network
> node src/check-versions.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'check-node-version'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kkn/src/github.com/streamr-dev/network/src/check-versions.js:1:77)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @streamr/streamr-p2p-network@1.0.3 requirements-check: `node src/check-versions.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @streamr/streamr-p2p-network@1.0.3 requirements-check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kkn/.npm/_logs/2018-09-19T09_11_11_920Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @streamr/streamr-p2p-network@1.0.3 preinstall: `npm run requirements-check`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @streamr/streamr-p2p-network@1.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kkn/.npm/_logs/2018-09-19T09_11_11_952Z-debug.log
```

2018-09-19 09:25 UTC, kare commented on README.md
> +
Perhaps we can work around this with something like:
Update README with "npm install -g check-node-version"

scripts: {
    preinstall: "check-node-version --node '>= 8.12.0' && ...",
}

2018-09-19 09:26 UTC, kare requested changes
Check comments!

2018-09-20 10:31 UTC, harbu commented on package.json
> +    "check-node-version": "^3.2.0",
Fixed. Btw should this be a devDependency instead of dependency?

2018-09-20 10:42 UTC, harbu commented
- I put exact version of the `check-node-version` in package.json file.
- I took the liberty of moving the script to the bin folder since no one objected. 😶

2018-09-20 10:43 UTC, harbu commented on README.md
> +
You are saying that even after installing the module globally on your system, the `require` will not work?

2018-09-21 11:46 UTC, kare commented on README.md
> +
@harbu Yeah that's what happens. Just tried it again

I've found this: https://github.com/npm/npm/issues/20434 I think this is the issue we have experienced when running "npm install"  and observing changes in package-lock.json even though package.json is unmodified. It seems to be a non issue. Also learned about "npm ci".

2018-09-21 13:52 UTC, merged